// Generated by tools/fill_stress_grammar.js
window.STRESS_GRAMMAR_PATCH = [
  {
    "id": 406,
    "ipa": "abecedAr",
    "hint": "名词 · 复数待核对: abecedare"
  },
  {
    "id": 407,
    "ipa": "absolvEnt",
    "hint": "名词 · 复数待核对: absolvente"
  },
  {
    "id": 408,
    "ipa": "acadEmie",
    "hint": "名词 · 复数待核对: academii"
  },
  {
    "id": 409,
    "ipa": "Acces",
    "hint": "名词 · 复数待核对: accese"
  },
  {
    "id": 410,
    "ipa": "accidEnt",
    "hint": "名词 · 复数待核对: accidente"
  },
  {
    "id": 411,
    "ipa": "Acord",
    "hint": "名词 · 复数待核对: acorde"
  },
  {
    "id": 412,
    "ipa": "activitAte",
    "hint": "名词 · 复数: activități"
  },
  {
    "id": 413,
    "ipa": "Acum",
    "hint": "副词 · 不变"
  },
  {
    "id": 414,
    "ipa": "Adânc",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 415,
    "ipa": "Adult",
    "hint": "名词 · 复数待核对: adulte"
  },
  {
    "id": 416,
    "ipa": "AEr",
    "hint": "名词 · 复数待核对: aere"
  },
  {
    "id": 417,
    "ipa": "afacEre",
    "hint": "名词 · 复数待核对: afaceri"
  },
  {
    "id": 418,
    "ipa": "agEndă",
    "hint": "名词 · 复数: agende"
  },
  {
    "id": 419,
    "ipa": "ajUtor",
    "hint": "名词 · 复数待核对: ajutoare"
  },
  {
    "id": 420,
    "ipa": "alArmă",
    "hint": "名词 · 复数: alarme"
  },
  {
    "id": 421,
    "ipa": "alIment",
    "hint": "名词 · 复数: alimente"
  },
  {
    "id": 422,
    "ipa": "ambulAnță",
    "hint": "名词 · 复数: ambulanțe"
  },
  {
    "id": 423,
    "ipa": "amintIre",
    "hint": "名词 · 复数待核对: amintiri"
  },
  {
    "id": 424,
    "ipa": "analIză",
    "hint": "名词 · 复数: analize"
  },
  {
    "id": 425,
    "ipa": "anAnas",
    "hint": "名词 · 复数待核对: ananase"
  },
  {
    "id": 426,
    "ipa": "apartAment",
    "hint": "名词 · 复数: apartamente"
  },
  {
    "id": 427,
    "ipa": "apEtit",
    "hint": "名词 · 复数待核对: apetite"
  },
  {
    "id": 428,
    "ipa": "aprIlie",
    "hint": "副词 · 不变"
  },
  {
    "id": 429,
    "ipa": "Argint",
    "hint": "名词 · 复数待核对: arginte"
  },
  {
    "id": 430,
    "ipa": "armAtă",
    "hint": "名词 · 复数: armate"
  },
  {
    "id": 431,
    "ipa": "arOmă",
    "hint": "名词 · 复数: arome"
  },
  {
    "id": 432,
    "ipa": "ascensOr",
    "hint": "名词 · 复数待核对: ascensore"
  },
  {
    "id": 433,
    "ipa": "asistEnt",
    "hint": "名词 · 复数待核对: asistente"
  },
  {
    "id": 434,
    "ipa": "Atac",
    "hint": "名词 · 复数待核对: atace"
  },
  {
    "id": 435,
    "ipa": "atEnție",
    "hint": "名词 · 复数: atenții"
  },
  {
    "id": 436,
    "ipa": "AUgust",
    "hint": "副词 · 不变"
  },
  {
    "id": 437,
    "ipa": "AUtor",
    "hint": "名词 · 复数待核对: autoare"
  },
  {
    "id": 438,
    "ipa": "autostrAdă",
    "hint": "名词 · 复数: autostrade"
  },
  {
    "id": 439,
    "ipa": "Avans",
    "hint": "名词 · 复数待核对: avanse"
  },
  {
    "id": 440,
    "ipa": "avAntaj",
    "hint": "名词 · 复数待核对: avantaje"
  },
  {
    "id": 441,
    "ipa": "avertizAre",
    "hint": "名词 · 复数待核对: avertizari"
  },
  {
    "id": 442,
    "ipa": "baghEtă",
    "hint": "名词 · 复数: baghete"
  },
  {
    "id": 443,
    "ipa": "bAlcon",
    "hint": "名词 · 复数待核对: balcone"
  },
  {
    "id": 444,
    "ipa": "balEnă",
    "hint": "名词 · 复数: balene"
  },
  {
    "id": 445,
    "ipa": "bArcă",
    "hint": "名词 · 复数: barce"
  },
  {
    "id": 446,
    "ipa": "batErie",
    "hint": "名词 · 复数待核对: baterii"
  },
  {
    "id": 447,
    "ipa": "bĂIAt",
    "hint": "名词 · 复数待核对: băiate"
  },
  {
    "id": 448,
    "ipa": "bĂtrân",
    "hint": "名词 · 复数待核对: bătrâne"
  },
  {
    "id": 449,
    "ipa": "bibliogrAfie",
    "hint": "名词 · 复数待核对: bibliografii"
  },
  {
    "id": 450,
    "ipa": "bIlet",
    "hint": "名词 · 复数待核对: bilete"
  },
  {
    "id": 451,
    "ipa": "bIrou",
    "hint": "名词 · 复数待核对: birouri"
  },
  {
    "id": 452,
    "ipa": "bIscuit",
    "hint": "名词 · 复数待核对: biscuite"
  },
  {
    "id": 453,
    "ipa": "blOc",
    "hint": "名词 · 复数待核对: bloce"
  },
  {
    "id": 454,
    "ipa": "bOAlă",
    "hint": "名词 · 复数: boale"
  },
  {
    "id": 455,
    "ipa": "bombOAnă",
    "hint": "名词 · 复数: bomboane"
  },
  {
    "id": 456,
    "ipa": "bOrd",
    "hint": "名词 · 复数待核对: borde"
  },
  {
    "id": 457,
    "ipa": "brățAră",
    "hint": "名词 · 复数: brățare"
  },
  {
    "id": 458,
    "ipa": "brutĂrie",
    "hint": "名词 · 复数待核对: brutării"
  },
  {
    "id": 459,
    "ipa": "bucUrie",
    "hint": "名词 · 复数待核对: bucurii"
  },
  {
    "id": 460,
    "ipa": "bulEtin",
    "hint": "名词 · 复数待核对: buletine"
  },
  {
    "id": 461,
    "ipa": "bUton",
    "hint": "名词 · 复数待核对: butone"
  },
  {
    "id": 462,
    "ipa": "cabAnă",
    "hint": "名词 · 复数: cabane"
  },
  {
    "id": 463,
    "ipa": "cAdă",
    "hint": "名词 · 复数: cade"
  },
  {
    "id": 464,
    "ipa": "cAIEt",
    "hint": "名词 · 复数待核对: caiete"
  },
  {
    "id": 465,
    "ipa": "calendAr",
    "hint": "副词 · 不变"
  },
  {
    "id": 466,
    "ipa": "calitAte",
    "hint": "名词 · 复数: calități"
  },
  {
    "id": 467,
    "ipa": "campAnie",
    "hint": "名词 · 复数待核对: campanii"
  },
  {
    "id": 468,
    "ipa": "canAl",
    "hint": "名词 · 复数待核对: canale"
  },
  {
    "id": 469,
    "ipa": "cApac",
    "hint": "名词 · 复数待核对: capace"
  },
  {
    "id": 470,
    "ipa": "carActer",
    "hint": "名词 · 复数待核对: caractere"
  },
  {
    "id": 471,
    "ipa": "carIEră",
    "hint": "名词 · 复数: cariere"
  },
  {
    "id": 472,
    "ipa": "cArtier",
    "hint": "名词 · 复数待核对: cartiere"
  },
  {
    "id": 473,
    "ipa": "castravEte",
    "hint": "名词 · 复数待核对: castraveti"
  },
  {
    "id": 474,
    "ipa": "catAlog",
    "hint": "名词 · 复数待核对: cataloge"
  },
  {
    "id": 475,
    "ipa": "cAzier",
    "hint": "名词 · 复数待核对: caziere"
  },
  {
    "id": 476,
    "ipa": "căldUră",
    "hint": "名词 · 复数: căldure"
  },
  {
    "id": 477,
    "ipa": "cĂmin",
    "hint": "名词 · 复数待核对: cămine"
  },
  {
    "id": 478,
    "ipa": "cântAr",
    "hint": "名词 · 复数待核对: cântare"
  },
  {
    "id": 479,
    "ipa": "cÂrnat",
    "hint": "名词 · 复数待核对: cârnate"
  },
  {
    "id": 480,
    "ipa": "cEApă",
    "hint": "名词 · 复数: ceape"
  },
  {
    "id": 481,
    "ipa": "cEAs",
    "hint": "副词 · 不变"
  },
  {
    "id": 482,
    "ipa": "cerEre",
    "hint": "名词 · 复数待核对: cereri"
  },
  {
    "id": 483,
    "ipa": "certifIcat",
    "hint": "名词 · 复数待核对: certificate"
  },
  {
    "id": 484,
    "ipa": "cheltUIAlă",
    "hint": "名词 · 复数: cheltuiale"
  },
  {
    "id": 485,
    "ipa": "chIrie",
    "hint": "名词 · 复数待核对: chirii"
  },
  {
    "id": 486,
    "ipa": "cIOrbă",
    "hint": "名词 · 复数: ciorbe"
  },
  {
    "id": 487,
    "ipa": "ciupErcă",
    "hint": "名词 · 复数: ciuperce"
  },
  {
    "id": 488,
    "ipa": "clădIre",
    "hint": "名词 · 复数待核对: clădiri"
  },
  {
    "id": 489,
    "ipa": "cOAdă",
    "hint": "名词 · 复数: coade"
  },
  {
    "id": 490,
    "ipa": "cOAjă",
    "hint": "名词 · 复数: coaje"
  },
  {
    "id": 491,
    "ipa": "cofetĂrie",
    "hint": "名词 · 复数待核对: cofetării"
  },
  {
    "id": 492,
    "ipa": "colEgiu",
    "hint": "名词 · 复数待核对: colegii"
  },
  {
    "id": 493,
    "ipa": "cOlind",
    "hint": "名词 · 复数待核对: colinde"
  },
  {
    "id": 494,
    "ipa": "comAndă",
    "hint": "名词 · 复数: comande"
  },
  {
    "id": 495,
    "ipa": "cOmerț",
    "hint": "名词 · 复数待核对: comerțe"
  },
  {
    "id": 496,
    "ipa": "compAnie",
    "hint": "名词 · 复数待核对: companii"
  },
  {
    "id": 497,
    "ipa": "competIție",
    "hint": "名词 · 复数: competiții"
  },
  {
    "id": 498,
    "ipa": "comportAment",
    "hint": "名词 · 复数: comportamente"
  },
  {
    "id": 499,
    "ipa": "conclUzie",
    "hint": "名词 · 复数待核对: concluzii"
  },
  {
    "id": 500,
    "ipa": "conducEre",
    "hint": "名词 · 复数待核对: conduceri"
  },
  {
    "id": 501,
    "ipa": "conferInță",
    "hint": "名词 · 复数: conferințe"
  },
  {
    "id": 502,
    "ipa": "consIliu",
    "hint": "名词 · 复数待核对: consilii"
  },
  {
    "id": 503,
    "ipa": "cOntor",
    "hint": "名词 · 复数待核对: contoare"
  },
  {
    "id": 504,
    "ipa": "conțInut",
    "hint": "名词 · 复数待核对: conținute"
  },
  {
    "id": 505,
    "ipa": "copErtă",
    "hint": "名词 · 复数: coperte"
  },
  {
    "id": 506,
    "ipa": "coridOr",
    "hint": "名词 · 复数待核对: coridore"
  },
  {
    "id": 507,
    "ipa": "cOstum",
    "hint": "名词 · 复数待核对: costume"
  },
  {
    "id": 508,
    "ipa": "cratIță",
    "hint": "名词 · 复数: cratițe"
  },
  {
    "id": 509,
    "ipa": "crEIEr",
    "hint": "名词 · 复数待核对: creiere"
  },
  {
    "id": 510,
    "ipa": "creștEre",
    "hint": "名词 · 复数待核对: creșteri"
  },
  {
    "id": 511,
    "ipa": "crIză",
    "hint": "名词 · 复数: crize"
  },
  {
    "id": 512,
    "ipa": "cUIEr",
    "hint": "名词 · 复数待核对: cuiere"
  },
  {
    "id": 513,
    "ipa": "cultUră",
    "hint": "名词 · 复数: culture"
  },
  {
    "id": 514,
    "ipa": "cUraj",
    "hint": "名词 · 复数待核对: curaje"
  },
  {
    "id": 515,
    "ipa": "curEnt",
    "hint": "名词 · 复数待核对: curente"
  },
  {
    "id": 516,
    "ipa": "cUrte",
    "hint": "名词 · 复数待核对: curti"
  },
  {
    "id": 517,
    "ipa": "cUtie",
    "hint": "名词 · 复数待核对: cutii"
  },
  {
    "id": 518,
    "ipa": "datOrie",
    "hint": "名词 · 复数待核对: datorii"
  },
  {
    "id": 519,
    "ipa": "decEmbrie",
    "hint": "副词 · 不变"
  },
  {
    "id": 520,
    "ipa": "decIzie",
    "hint": "名词 · 复数待核对: decizii"
  },
  {
    "id": 521,
    "ipa": "declarAție",
    "hint": "名词 · 复数: declarații"
  },
  {
    "id": 522,
    "ipa": "dEget",
    "hint": "名词 · 复数待核对: degete"
  },
  {
    "id": 523,
    "ipa": "dEjun",
    "hint": "名词 · 复数待核对: dejune"
  },
  {
    "id": 524,
    "ipa": "demIsol",
    "hint": "名词 · 复数待核对: demisole"
  },
  {
    "id": 525,
    "ipa": "dEsen",
    "hint": "名词 · 复数待核对: desene"
  },
  {
    "id": 526,
    "ipa": "detAliu",
    "hint": "名词 · 复数待核对: detalii"
  },
  {
    "id": 527,
    "ipa": "dezavAntaj",
    "hint": "名词 · 复数待核对: dezavantaje"
  },
  {
    "id": 528,
    "ipa": "dIAlog",
    "hint": "名词 · 复数待核对: dialoge"
  },
  {
    "id": 529,
    "ipa": "diferEnță",
    "hint": "名词 · 复数: diferențe"
  },
  {
    "id": 530,
    "ipa": "diminEAță",
    "hint": "副词 · 不变"
  },
  {
    "id": 531,
    "ipa": "dirEctor",
    "hint": "名词 · 复数待核对: directoare"
  },
  {
    "id": 532,
    "ipa": "discUție",
    "hint": "名词 · 复数: discuții"
  },
  {
    "id": 533,
    "ipa": "distAnță",
    "hint": "名词 · 复数: distanțe"
  },
  {
    "id": 534,
    "ipa": "distribUție",
    "hint": "名词 · 复数: distribuții"
  },
  {
    "id": 535,
    "ipa": "dovAdă",
    "hint": "名词 · 复数: dovade"
  },
  {
    "id": 536,
    "ipa": "dUlap",
    "hint": "名词 · 复数待核对: dulape"
  },
  {
    "id": 537,
    "ipa": "duminIcă",
    "hint": "副词 · 不变"
  },
  {
    "id": 538,
    "ipa": "echilIbru",
    "hint": "名词 · 复数待核对: echilibruri"
  },
  {
    "id": 539,
    "ipa": "econOmie",
    "hint": "名词 · 复数待核对: economii"
  },
  {
    "id": 540,
    "ipa": "Efort",
    "hint": "名词 · 复数待核对: eforte"
  },
  {
    "id": 541,
    "ipa": "emOție",
    "hint": "名词 · 复数: emoții"
  },
  {
    "id": 542,
    "ipa": "enErgie",
    "hint": "名词 · 复数待核对: energii"
  },
  {
    "id": 543,
    "ipa": "erOAre",
    "hint": "名词 · 复数待核对: eroari"
  },
  {
    "id": 544,
    "ipa": "Etaj",
    "hint": "名词 · 复数待核对: etaje"
  },
  {
    "id": 545,
    "ipa": "etichEtă",
    "hint": "名词 · 复数: etichete"
  },
  {
    "id": 546,
    "ipa": "evenIment",
    "hint": "名词 · 复数: evenimente"
  },
  {
    "id": 547,
    "ipa": "exEmplu",
    "hint": "名词 · 复数待核对: exempluri"
  },
  {
    "id": 548,
    "ipa": "experIEnță",
    "hint": "名词 · 复数: experiențe"
  },
  {
    "id": 549,
    "ipa": "explicAție",
    "hint": "名词 · 复数: explicații"
  },
  {
    "id": 550,
    "ipa": "famIlie",
    "hint": "名词 · 复数待核对: familii"
  },
  {
    "id": 551,
    "ipa": "febrUArie",
    "hint": "副词 · 不变"
  },
  {
    "id": 552,
    "ipa": "felicitAre",
    "hint": "名词 · 复数待核对: felicitari"
  },
  {
    "id": 553,
    "ipa": "fericIre",
    "hint": "名词 · 复数待核对: fericiri"
  },
  {
    "id": 554,
    "ipa": "festivAl",
    "hint": "名词 · 复数待核对: festivale"
  },
  {
    "id": 555,
    "ipa": "fIșier",
    "hint": "名词 · 复数待核对: fișiere"
  },
  {
    "id": 556,
    "ipa": "flacĂră",
    "hint": "名词 · 复数: flacăre"
  },
  {
    "id": 557,
    "ipa": "formulAr",
    "hint": "名词 · 复数待核对: formulare"
  },
  {
    "id": 558,
    "ipa": "fotOliu",
    "hint": "名词 · 复数待核对: fotolii"
  },
  {
    "id": 559,
    "ipa": "frIg",
    "hint": "名词 · 复数待核对: frige"
  },
  {
    "id": 560,
    "ipa": "friptUră",
    "hint": "名词 · 复数: fripture"
  },
  {
    "id": 561,
    "ipa": "fUncție",
    "hint": "名词 · 复数: funcții"
  },
  {
    "id": 562,
    "ipa": "garAnție",
    "hint": "名词 · 复数: garanții"
  },
  {
    "id": 563,
    "ipa": "gălEAtă",
    "hint": "名词 · 复数: găleate"
  },
  {
    "id": 564,
    "ipa": "gÂnd",
    "hint": "名词 · 复数待核对: gânde"
  },
  {
    "id": 565,
    "ipa": "geamAntan",
    "hint": "名词 · 复数待核对: geamantane"
  },
  {
    "id": 566,
    "ipa": "gEm",
    "hint": "名词 · 复数待核对: geme"
  },
  {
    "id": 567,
    "ipa": "genUnchi",
    "hint": "名词 · 复数待核对: genunchii"
  },
  {
    "id": 568,
    "ipa": "gEst",
    "hint": "名词 · 复数待核对: geste"
  },
  {
    "id": 569,
    "ipa": "ghEAță",
    "hint": "名词 · 复数: gheațe"
  },
  {
    "id": 570,
    "ipa": "ghId",
    "hint": "名词 · 复数待核对: ghide"
  },
  {
    "id": 571,
    "ipa": "ghIOzdan",
    "hint": "名词 · 复数待核对: ghiozdane"
  },
  {
    "id": 572,
    "ipa": "glUmă",
    "hint": "名词 · 复数: glume"
  },
  {
    "id": 573,
    "ipa": "grădInă",
    "hint": "名词 · 复数: grădine"
  },
  {
    "id": 574,
    "ipa": "greutAte",
    "hint": "名词 · 复数: greutăți"
  },
  {
    "id": 575,
    "ipa": "grIjă",
    "hint": "名词 · 复数: grije"
  },
  {
    "id": 576,
    "ipa": "grUp",
    "hint": "名词 · 复数待核对: grupe"
  },
  {
    "id": 577,
    "ipa": "gUst",
    "hint": "名词 · 复数待核对: guste"
  },
  {
    "id": 578,
    "ipa": "hAInă",
    "hint": "名词 · 复数: haine"
  },
  {
    "id": 579,
    "ipa": "hÂrtie",
    "hint": "名词 · 复数待核对: hârtii"
  },
  {
    "id": 580,
    "ipa": "hArtă",
    "hint": "名词 · 复数: harte"
  },
  {
    "id": 581,
    "ipa": "hotărÂre",
    "hint": "名词 · 复数待核对: hotărâri"
  },
  {
    "id": 582,
    "ipa": "Idee",
    "hint": "名词 · 复数待核对: idei"
  },
  {
    "id": 583,
    "ipa": "ieșIre",
    "hint": "名词 · 复数待核对: ieșiri"
  },
  {
    "id": 584,
    "ipa": "imagIne",
    "hint": "名词 · 复数待核对: imagini"
  },
  {
    "id": 585,
    "ipa": "Impact",
    "hint": "名词 · 复数待核对: impacte"
  },
  {
    "id": 586,
    "ipa": "imprEsie",
    "hint": "名词 · 复数待核对: impresii"
  },
  {
    "id": 587,
    "ipa": "incEndiu",
    "hint": "名词 · 复数待核对: incendii"
  },
  {
    "id": 588,
    "ipa": "indUstrie",
    "hint": "名词 · 复数待核对: industrii"
  },
  {
    "id": 589,
    "ipa": "informAție",
    "hint": "名词 · 复数: informații"
  },
  {
    "id": 590,
    "ipa": "ingredIEnt",
    "hint": "名词 · 复数待核对: ingrediente"
  },
  {
    "id": 591,
    "ipa": "inspEctor",
    "hint": "名词 · 复数待核对: inspectoare"
  },
  {
    "id": 592,
    "ipa": "instrucțIUne",
    "hint": "名词 · 复数: instrucțiuni"
  },
  {
    "id": 593,
    "ipa": "instrUment",
    "hint": "名词 · 复数: instrumente"
  },
  {
    "id": 594,
    "ipa": "intEnție",
    "hint": "名词 · 复数: intenții"
  },
  {
    "id": 595,
    "ipa": "intEres",
    "hint": "名词 · 复数待核对: interese"
  },
  {
    "id": 596,
    "ipa": "invitAție",
    "hint": "名词 · 复数: invitații"
  },
  {
    "id": 597,
    "ipa": "ianUArie",
    "hint": "副词 · 不变"
  },
  {
    "id": 598,
    "ipa": "IUnie",
    "hint": "副词 · 不变"
  },
  {
    "id": 599,
    "ipa": "IUlie",
    "hint": "副词 · 不变"
  },
  {
    "id": 600,
    "ipa": "izvOr",
    "hint": "名词 · 复数待核对: izvore"
  },
  {
    "id": 601,
    "ipa": "jachEtă",
    "hint": "名词 · 复数: jachete"
  },
  {
    "id": 602,
    "ipa": "jOI",
    "hint": "副词 · 不变"
  },
  {
    "id": 603,
    "ipa": "jucĂrie",
    "hint": "名词 · 复数待核对: jucării"
  },
  {
    "id": 604,
    "ipa": "judecĂtor",
    "hint": "名词 · 复数待核对: judecătoare"
  },
  {
    "id": 605,
    "ipa": "laborAtor",
    "hint": "名词 · 复数待核对: laboratoare"
  },
  {
    "id": 606,
    "ipa": "lAnț",
    "hint": "名词 · 复数待核对: lanțe"
  },
  {
    "id": 607,
    "ipa": "legătUră",
    "hint": "名词 · 复数: legăture"
  },
  {
    "id": 608,
    "ipa": "lEmn",
    "hint": "名词 · 复数待核对: lemne"
  },
  {
    "id": 609,
    "ipa": "lenjErie",
    "hint": "名词 · 复数待核对: lenjerii"
  },
  {
    "id": 610,
    "ipa": "libertAte",
    "hint": "名词 · 复数: libertăți"
  },
  {
    "id": 611,
    "ipa": "lInie",
    "hint": "名词 · 复数待核对: linii"
  },
  {
    "id": 612,
    "ipa": "lingurIță",
    "hint": "名词 · 复数: lingurițe"
  },
  {
    "id": 613,
    "ipa": "lIstă",
    "hint": "名词 · 复数: liste"
  },
  {
    "id": 614,
    "ipa": "locUInță",
    "hint": "名词 · 复数: locuințe"
  },
  {
    "id": 615,
    "ipa": "lucrĂtor",
    "hint": "名词 · 复数待核对: lucrătoare"
  },
  {
    "id": 616,
    "ipa": "lUni",
    "hint": "副词 · 不变"
  },
  {
    "id": 617,
    "ipa": "lumInă",
    "hint": "名词 · 复数: lumine"
  },
  {
    "id": 618,
    "ipa": "magAzin",
    "hint": "名词 · 复数待核对: magazine"
  },
  {
    "id": 619,
    "ipa": "maionEză",
    "hint": "名词 · 复数: maioneze"
  },
  {
    "id": 620,
    "ipa": "manAger",
    "hint": "名词 · 复数待核对: managere"
  },
  {
    "id": 621,
    "ipa": "mArtie",
    "hint": "副词 · 不变"
  },
  {
    "id": 622,
    "ipa": "mArți",
    "hint": "副词 · 不变"
  },
  {
    "id": 623,
    "ipa": "mașInă",
    "hint": "名词 · 复数: mașine"
  },
  {
    "id": 624,
    "ipa": "măsUră",
    "hint": "名词 · 复数: măsure"
  },
  {
    "id": 625,
    "ipa": "medAlie",
    "hint": "名词 · 复数待核对: medalii"
  },
  {
    "id": 626,
    "ipa": "mEdiu",
    "hint": "名词 · 复数待核对: medii"
  },
  {
    "id": 627,
    "ipa": "mEmbru",
    "hint": "名词 · 复数待核对: membruri"
  },
  {
    "id": 628,
    "ipa": "mEniu",
    "hint": "名词 · 复数待核对: menii"
  },
  {
    "id": 629,
    "ipa": "mesErie",
    "hint": "名词 · 复数待核对: meserii"
  },
  {
    "id": 630,
    "ipa": "metOdă",
    "hint": "名词 · 复数: metode"
  },
  {
    "id": 631,
    "ipa": "miercUri",
    "hint": "副词 · 不变"
  },
  {
    "id": 632,
    "ipa": "mIjloc",
    "hint": "副词 · 不变"
  },
  {
    "id": 633,
    "ipa": "minoritAte",
    "hint": "名词 · 复数: minorități"
  },
  {
    "id": 634,
    "ipa": "mInut",
    "hint": "副词 · 不变"
  },
  {
    "id": 635,
    "ipa": "mirOs",
    "hint": "名词 · 复数待核对: mirose"
  },
  {
    "id": 636,
    "ipa": "mOdel",
    "hint": "名词 · 复数待核对: modele"
  },
  {
    "id": 637,
    "ipa": "monItor",
    "hint": "名词 · 复数待核对: monitoare"
  },
  {
    "id": 638,
    "ipa": "mOrcov",
    "hint": "名词 · 复数待核对: morcove"
  },
  {
    "id": 639,
    "ipa": "motIv",
    "hint": "名词 · 复数待核对: motive"
  },
  {
    "id": 640,
    "ipa": "mUșchi",
    "hint": "名词 · 复数待核对: mușchii"
  },
  {
    "id": 641,
    "ipa": "naștEre",
    "hint": "名词 · 复数待核对: nașteri"
  },
  {
    "id": 642,
    "ipa": "nEpot",
    "hint": "名词 · 复数待核对: nepote"
  },
  {
    "id": 643,
    "ipa": "nIvel",
    "hint": "名词 · 复数待核对: nivele"
  },
  {
    "id": 644,
    "ipa": "nOIEmbrie",
    "hint": "副词 · 不变"
  },
  {
    "id": 645,
    "ipa": "nOr",
    "hint": "名词 · 复数待核对: nore"
  },
  {
    "id": 646,
    "ipa": "nOtă",
    "hint": "名词 · 复数: note"
  },
  {
    "id": 647,
    "ipa": "obIcei",
    "hint": "名词 · 复数待核对: obiceii"
  },
  {
    "id": 648,
    "ipa": "Obiect",
    "hint": "名词 · 复数待核对: obiecte"
  },
  {
    "id": 649,
    "ipa": "obosEAlă",
    "hint": "名词 · 复数待核对: oboseli"
  },
  {
    "id": 650,
    "ipa": "ocAzie",
    "hint": "名词 · 复数待核对: ocazii"
  },
  {
    "id": 651,
    "ipa": "octOmbrie",
    "hint": "副词 · 不变"
  },
  {
    "id": 652,
    "ipa": "ofErtă",
    "hint": "名词 · 复数: oferte"
  },
  {
    "id": 653,
    "ipa": "oglIndă",
    "hint": "名词 · 复数: oglinde"
  },
  {
    "id": 654,
    "ipa": "opInie",
    "hint": "名词 · 复数待核对: opinii"
  },
  {
    "id": 655,
    "ipa": "ordIne",
    "hint": "名词 · 复数待核对: ordini"
  },
  {
    "id": 656,
    "ipa": "organizAție",
    "hint": "名词 · 复数: organizații"
  },
  {
    "id": 657,
    "ipa": "orIzont",
    "hint": "名词 · 复数待核对: orizonte"
  },
  {
    "id": 658,
    "ipa": "ospătAr",
    "hint": "名词 · 复数待核对: ospătare"
  },
  {
    "id": 659,
    "ipa": "pAchet",
    "hint": "名词 · 复数待核对: pachete"
  },
  {
    "id": 660,
    "ipa": "pagInă",
    "hint": "名词 · 复数: pagine"
  },
  {
    "id": 661,
    "ipa": "parcAre",
    "hint": "名词 · 复数待核对: parcari"
  },
  {
    "id": 662,
    "ipa": "participAnt",
    "hint": "名词 · 复数待核对: participați"
  },
  {
    "id": 663,
    "ipa": "pasAger",
    "hint": "名词 · 复数待核对: pasagere"
  },
  {
    "id": 664,
    "ipa": "pAstă",
    "hint": "名词 · 复数: paste"
  },
  {
    "id": 665,
    "ipa": "pălĂrie",
    "hint": "名词 · 复数待核对: pălării"
  },
  {
    "id": 666,
    "ipa": "părEre",
    "hint": "名词 · 复数待核对: păreri"
  },
  {
    "id": 667,
    "ipa": "pătUră",
    "hint": "名词 · 复数: păture"
  },
  {
    "id": 668,
    "ipa": "perEte",
    "hint": "名词 · 复数待核对: pereti"
  },
  {
    "id": 669,
    "ipa": "perIcol",
    "hint": "名词 · 复数待核对: pericole"
  },
  {
    "id": 670,
    "ipa": "perIOAdă",
    "hint": "副词 · 不变"
  },
  {
    "id": 671,
    "ipa": "pErmis",
    "hint": "名词 · 复数待核对: permise"
  },
  {
    "id": 672,
    "ipa": "pEscuit",
    "hint": "名词 · 复数待核对: pescuite"
  },
  {
    "id": 673,
    "ipa": "pIEpt",
    "hint": "名词 · 复数待核对: piepte"
  },
  {
    "id": 674,
    "ipa": "pIlot",
    "hint": "名词 · 复数待核对: pilote"
  },
  {
    "id": 675,
    "ipa": "piscInă",
    "hint": "名词 · 复数: piscine"
  },
  {
    "id": 676,
    "ipa": "plAjă",
    "hint": "名词 · 复数: plaje"
  },
  {
    "id": 677,
    "ipa": "plAtă",
    "hint": "名词 · 复数: plate"
  },
  {
    "id": 678,
    "ipa": "plimbAre",
    "hint": "名词 · 复数待核对: plimbari"
  },
  {
    "id": 679,
    "ipa": "pOArtă",
    "hint": "名词 · 复数: poarte"
  },
  {
    "id": 680,
    "ipa": "politIcian",
    "hint": "名词 · 复数待核对: politiciane"
  },
  {
    "id": 681,
    "ipa": "popOr",
    "hint": "名词 · 复数待核对: popore"
  },
  {
    "id": 682,
    "ipa": "pOrumb",
    "hint": "名词 · 复数待核对: porumbe"
  },
  {
    "id": 683,
    "ipa": "posibilitAte",
    "hint": "名词 · 复数: posibilități"
  },
  {
    "id": 684,
    "ipa": "poșEtă",
    "hint": "名词 · 复数: poșete"
  },
  {
    "id": 685,
    "ipa": "prÂnz",
    "hint": "名词 · 复数待核对: prânze"
  },
  {
    "id": 686,
    "ipa": "prEț",
    "hint": "名词 · 复数待核对: prețe"
  },
  {
    "id": 687,
    "ipa": "prietEne",
    "hint": "名词 · 复数待核对: prieteni"
  },
  {
    "id": 688,
    "ipa": "privIre",
    "hint": "名词 · 复数待核对: priviri"
  },
  {
    "id": 689,
    "ipa": "prodUcție",
    "hint": "名词 · 复数: producții"
  },
  {
    "id": 690,
    "ipa": "prOdus",
    "hint": "名词 · 复数待核对: produse"
  },
  {
    "id": 691,
    "ipa": "profEsie",
    "hint": "名词 · 复数待核对: profesii"
  },
  {
    "id": 692,
    "ipa": "programAre",
    "hint": "名词 · 复数待核对: programari"
  },
  {
    "id": 693,
    "ipa": "prOgres",
    "hint": "名词 · 复数待核对: progrese"
  },
  {
    "id": 694,
    "ipa": "proprietAr",
    "hint": "名词 · 复数待核对: proprietare"
  },
  {
    "id": 695,
    "ipa": "prosperitAte",
    "hint": "名词 · 复数: prosperități"
  },
  {
    "id": 696,
    "ipa": "protEcție",
    "hint": "名词 · 复数: protecții"
  },
  {
    "id": 697,
    "ipa": "publicitAte",
    "hint": "名词 · 复数: publicități"
  },
  {
    "id": 698,
    "ipa": "pUnct",
    "hint": "名词 · 复数待核对: puncte"
  },
  {
    "id": 699,
    "ipa": "putEre",
    "hint": "名词 · 复数待核对: puteri"
  },
  {
    "id": 700,
    "ipa": "rAport",
    "hint": "名词 · 复数待核对: raporte"
  },
  {
    "id": 701,
    "ipa": "răbdAre",
    "hint": "名词 · 复数待核对: răbdari"
  },
  {
    "id": 702,
    "ipa": "răspundEre",
    "hint": "名词 · 复数待核对: răspunderi"
  },
  {
    "id": 703,
    "ipa": "recipIEnt",
    "hint": "名词 · 复数待核对: recipiente"
  },
  {
    "id": 704,
    "ipa": "reclAmă",
    "hint": "名词 · 复数: reclame"
  },
  {
    "id": 705,
    "ipa": "reducEre",
    "hint": "名词 · 复数待核对: reduceri"
  },
  {
    "id": 706,
    "ipa": "regUlă",
    "hint": "名词 · 复数: regule"
  },
  {
    "id": 707,
    "ipa": "relAție",
    "hint": "名词 · 复数: relații"
  },
  {
    "id": 708,
    "ipa": "reparAție",
    "hint": "名词 · 复数: reparații"
  },
  {
    "id": 709,
    "ipa": "rEțea",
    "hint": "名词 · 复数待核对: rețeai"
  },
  {
    "id": 710,
    "ipa": "rezUltat",
    "hint": "名词 · 复数待核对: rezultate"
  },
  {
    "id": 711,
    "ipa": "ridicAre",
    "hint": "名词 · 复数待核对: ridicari"
  },
  {
    "id": 712,
    "ipa": "rIsc",
    "hint": "名词 · 复数待核对: risce"
  },
  {
    "id": 713,
    "ipa": "rOchie",
    "hint": "名词 · 复数待核对: rochii"
  },
  {
    "id": 714,
    "ipa": "rOșie",
    "hint": "名词 · 复数待核对: roșii"
  },
  {
    "id": 715,
    "ipa": "rușIne",
    "hint": "名词 · 复数待核对: rușini"
  },
  {
    "id": 716,
    "ipa": "sâmbĂtă",
    "hint": "副词 · 不变"
  },
  {
    "id": 717,
    "ipa": "sAt",
    "hint": "名词 · 复数待核对: sate"
  },
  {
    "id": 718,
    "ipa": "scOp",
    "hint": "名词 · 复数待核对: scope"
  },
  {
    "id": 719,
    "ipa": "scrisOAre",
    "hint": "名词 · 复数待核对: scrisoari"
  },
  {
    "id": 720,
    "ipa": "scutIre",
    "hint": "名词 · 复数待核对: scutiri"
  },
  {
    "id": 721,
    "ipa": "sEAră",
    "hint": "副词 · 不变"
  },
  {
    "id": 722,
    "ipa": "sEcret",
    "hint": "名词 · 复数待核对: secrete"
  },
  {
    "id": 723,
    "ipa": "septEmbrie",
    "hint": "副词 · 不变"
  },
  {
    "id": 724,
    "ipa": "servIciu",
    "hint": "名词 · 复数待核对: servicii"
  },
  {
    "id": 725,
    "ipa": "sEmn",
    "hint": "名词 · 复数待核对: semne"
  },
  {
    "id": 726,
    "ipa": "semnAl",
    "hint": "名词 · 复数待核对: semnale"
  },
  {
    "id": 727,
    "ipa": "sentIment",
    "hint": "名词 · 复数: sentimente"
  },
  {
    "id": 728,
    "ipa": "sErie",
    "hint": "名词 · 复数待核对: serii"
  },
  {
    "id": 729,
    "ipa": "sertAr",
    "hint": "名词 · 复数待核对: sertare"
  },
  {
    "id": 730,
    "ipa": "sfAt",
    "hint": "名词 · 复数待核对: sfate"
  },
  {
    "id": 731,
    "ipa": "sigurAnță",
    "hint": "名词 · 复数: siguranțe"
  },
  {
    "id": 732,
    "ipa": "sIstem",
    "hint": "名词 · 复数待核对: sisteme"
  },
  {
    "id": 733,
    "ipa": "sitUAție",
    "hint": "名词 · 复数: situații"
  },
  {
    "id": 734,
    "ipa": "societAte",
    "hint": "名词 · 复数: societăți"
  },
  {
    "id": 735,
    "ipa": "solUție",
    "hint": "名词 · 复数: soluții"
  },
  {
    "id": 736,
    "ipa": "sperAnță",
    "hint": "名词 · 复数: speranțe"
  },
  {
    "id": 737,
    "ipa": "spUmă",
    "hint": "名词 · 复数: spume"
  },
  {
    "id": 738,
    "ipa": "stAre",
    "hint": "名词 · 复数待核对: stari"
  },
  {
    "id": 739,
    "ipa": "stAt",
    "hint": "名词 · 复数待核对: state"
  },
  {
    "id": 740,
    "ipa": "stEAg",
    "hint": "名词 · 复数待核对: steage"
  },
  {
    "id": 741,
    "ipa": "stIclă",
    "hint": "名词 · 复数: sticle"
  },
  {
    "id": 742,
    "ipa": "stIl",
    "hint": "名词 · 复数待核对: stile"
  },
  {
    "id": 743,
    "ipa": "strĂIn",
    "hint": "名词 · 复数待核对: străine"
  },
  {
    "id": 744,
    "ipa": "sUcces",
    "hint": "名词 · 复数待核对: succese"
  },
  {
    "id": 745,
    "ipa": "sUflet",
    "hint": "名词 · 复数待核对: suflete"
  },
  {
    "id": 746,
    "ipa": "sUmă",
    "hint": "名词 · 复数: sume"
  },
  {
    "id": 747,
    "ipa": "suprafAță",
    "hint": "名词 · 复数: suprafațe"
  },
  {
    "id": 748,
    "ipa": "surprIză",
    "hint": "名词 · 复数: surprize"
  },
  {
    "id": 749,
    "ipa": "tAblou",
    "hint": "名词 · 复数待核对: tablouri"
  },
  {
    "id": 750,
    "ipa": "tăcEre",
    "hint": "名词 · 复数待核对: tăceri"
  },
  {
    "id": 751,
    "ipa": "tAxă",
    "hint": "名词 · 复数: taxe"
  },
  {
    "id": 752,
    "ipa": "tehnolOgie",
    "hint": "名词 · 复数待核对: tehnologii"
  },
  {
    "id": 753,
    "ipa": "tEmă",
    "hint": "名词 · 复数: teme"
  },
  {
    "id": 754,
    "ipa": "tImp",
    "hint": "副词 · 不变"
  },
  {
    "id": 755,
    "ipa": "tinerEțe",
    "hint": "名词 · 复数待核对: tinereți"
  },
  {
    "id": 756,
    "ipa": "toalEtă",
    "hint": "名词 · 复数: toalete"
  },
  {
    "id": 757,
    "ipa": "tOrt",
    "hint": "名词 · 复数待核对: torte"
  },
  {
    "id": 758,
    "ipa": "tradIție",
    "hint": "名词 · 复数: tradiții"
  },
  {
    "id": 759,
    "ipa": "trafIc",
    "hint": "名词 · 复数待核对: trafice"
  },
  {
    "id": 760,
    "ipa": "tristEțe",
    "hint": "名词 · 复数待核对: tristeți"
  },
  {
    "id": 761,
    "ipa": "tUr",
    "hint": "名词 · 复数待核对: ture"
  },
  {
    "id": 762,
    "ipa": "uimIre",
    "hint": "名词 · 复数待核对: uimiri"
  },
  {
    "id": 763,
    "ipa": "Umăr",
    "hint": "名词 · 复数待核对: umăre"
  },
  {
    "id": 764,
    "ipa": "unitAte",
    "hint": "名词 · 复数: unități"
  },
  {
    "id": 765,
    "ipa": "urcAre",
    "hint": "名词 · 复数待核对: urcari"
  },
  {
    "id": 766,
    "ipa": "utilizAtor",
    "hint": "名词 · 复数待核对: utilizatoare"
  },
  {
    "id": 767,
    "ipa": "vacAnță",
    "hint": "名词 · 复数: vacanțe"
  },
  {
    "id": 768,
    "ipa": "valOAre",
    "hint": "名词 · 复数待核对: valoari"
  },
  {
    "id": 769,
    "ipa": "vânzĂtor",
    "hint": "名词 · 复数待核对: vânzătoare"
  },
  {
    "id": 770,
    "ipa": "varIAntă",
    "hint": "名词 · 复数: variante"
  },
  {
    "id": 771,
    "ipa": "vecinătAte",
    "hint": "名词 · 复数: vecinătăți"
  },
  {
    "id": 772,
    "ipa": "vedEre",
    "hint": "名词 · 复数待核对: vederi"
  },
  {
    "id": 773,
    "ipa": "verificAre",
    "hint": "名词 · 复数待核对: verificari"
  },
  {
    "id": 774,
    "ipa": "vIAță",
    "hint": "名词 · 复数: viațe"
  },
  {
    "id": 775,
    "ipa": "victOrie",
    "hint": "名词 · 复数待核对: victorii"
  },
  {
    "id": 776,
    "ipa": "vinEri",
    "hint": "副词 · 不变"
  },
  {
    "id": 777,
    "ipa": "vitEză",
    "hint": "名词 · 复数: viteze"
  },
  {
    "id": 778,
    "ipa": "vOce",
    "hint": "名词 · 复数待核对: voci"
  },
  {
    "id": 779,
    "ipa": "vOt",
    "hint": "名词 · 复数待核对: vote"
  },
  {
    "id": 780,
    "ipa": "zgOmot",
    "hint": "名词 · 复数待核对: zgomote"
  },
  {
    "id": 781,
    "ipa": "zOnă",
    "hint": "名词 · 复数: zone"
  },
  {
    "id": 782,
    "ipa": "abilitAte",
    "hint": "名词 · 复数: abilități"
  },
  {
    "id": 783,
    "ipa": "abonAment",
    "hint": "名词 · 复数: abonamente"
  },
  {
    "id": 784,
    "ipa": "absEnță",
    "hint": "名词 · 复数: absențe"
  },
  {
    "id": 785,
    "ipa": "Abuz",
    "hint": "名词 · 复数待核对: abuze"
  },
  {
    "id": 786,
    "ipa": "accEnt",
    "hint": "名词 · 复数待核对: accente"
  },
  {
    "id": 787,
    "ipa": "acceptAre",
    "hint": "名词 · 复数待核对: acceptari"
  },
  {
    "id": 788,
    "ipa": "acopEriș",
    "hint": "名词 · 复数待核对: acoperișe"
  },
  {
    "id": 789,
    "ipa": "acțIUne",
    "hint": "名词 · 复数: acțiuni"
  },
  {
    "id": 790,
    "ipa": "adEvăr",
    "hint": "名词 · 复数待核对: adevăre"
  },
  {
    "id": 791,
    "ipa": "administrAție",
    "hint": "名词 · 复数: administrații"
  },
  {
    "id": 792,
    "ipa": "adolescEnt",
    "hint": "名词 · 复数待核对: adolescente"
  },
  {
    "id": 793,
    "ipa": "adunAre",
    "hint": "名词 · 复数待核对: adunari"
  },
  {
    "id": 794,
    "ipa": "afirmAre",
    "hint": "名词 · 复数待核对: afirmari"
  },
  {
    "id": 795,
    "ipa": "agEnt",
    "hint": "名词 · 复数待核对: agente"
  },
  {
    "id": 796,
    "ipa": "agitAție",
    "hint": "名词 · 复数: agitații"
  },
  {
    "id": 797,
    "ipa": "agricultUră",
    "hint": "名词 · 复数: agriculture"
  },
  {
    "id": 798,
    "ipa": "Alee",
    "hint": "名词 · 复数待核对: alei"
  },
  {
    "id": 799,
    "ipa": "ambasadOr",
    "hint": "名词 · 复数待核对: ambasadore"
  },
  {
    "id": 800,
    "ipa": "ambasAda",
    "hint": "名词 · 复数待核对: ambasadai"
  },
  {
    "id": 801,
    "ipa": "amenajAre",
    "hint": "名词 · 复数待核对: amenajari"
  },
  {
    "id": 802,
    "ipa": "amEndă",
    "hint": "名词 · 复数: amende"
  },
  {
    "id": 803,
    "ipa": "amIAză",
    "hint": "副词 · 不变"
  },
  {
    "id": 804,
    "ipa": "amprEntă",
    "hint": "名词 · 复数: amprente"
  },
  {
    "id": 805,
    "ipa": "antrenAment",
    "hint": "名词 · 复数: antrenamente"
  },
  {
    "id": 806,
    "ipa": "Anunț",
    "hint": "名词 · 复数待核对: anunțe"
  },
  {
    "id": 807,
    "ipa": "apArat",
    "hint": "名词 · 复数待核对: aparate"
  },
  {
    "id": 808,
    "ipa": "apărAre",
    "hint": "名词 · 复数待核对: apărari"
  },
  {
    "id": 809,
    "ipa": "aprobAre",
    "hint": "名词 · 复数待核对: aprobari"
  },
  {
    "id": 810,
    "ipa": "arhItect",
    "hint": "名词 · 复数待核对: arhitecte"
  },
  {
    "id": 811,
    "ipa": "arIpă",
    "hint": "名词 · 复数: aripe"
  },
  {
    "id": 812,
    "ipa": "arhIvă",
    "hint": "名词 · 复数: arhive"
  },
  {
    "id": 813,
    "ipa": "artIcol",
    "hint": "名词 · 复数待核对: articole"
  },
  {
    "id": 814,
    "ipa": "asigurAre",
    "hint": "名词 · 复数待核对: asigurari"
  },
  {
    "id": 815,
    "ipa": "asocIAție",
    "hint": "名词 · 复数: asociații"
  },
  {
    "id": 816,
    "ipa": "atitudIne",
    "hint": "名词 · 复数待核对: atitudini"
  },
  {
    "id": 817,
    "ipa": "atrAcție",
    "hint": "名词 · 复数: atracții"
  },
  {
    "id": 818,
    "ipa": "audIEnță",
    "hint": "名词 · 复数: audiențe"
  },
  {
    "id": 819,
    "ipa": "autoritAte",
    "hint": "名词 · 复数: autorități"
  },
  {
    "id": 820,
    "ipa": "avertIsment",
    "hint": "名词 · 复数: avertismente"
  },
  {
    "id": 821,
    "ipa": "avOcat",
    "hint": "名词 · 复数待核对: avocate"
  },
  {
    "id": 822,
    "ipa": "Azil",
    "hint": "名词 · 复数待核对: azile"
  },
  {
    "id": 823,
    "ipa": "bAl",
    "hint": "名词 · 复数待核对: bale"
  },
  {
    "id": 824,
    "ipa": "bancnOtă",
    "hint": "名词 · 复数: bancnote"
  },
  {
    "id": 825,
    "ipa": "barIEră",
    "hint": "名词 · 复数: bariere"
  },
  {
    "id": 826,
    "ipa": "bAston",
    "hint": "名词 · 复数待核对: bastone"
  },
  {
    "id": 827,
    "ipa": "bazAAr",
    "hint": "名词 · 复数待核对: bazaare"
  },
  {
    "id": 828,
    "ipa": "bibliotecAr",
    "hint": "名词 · 复数待核对: bibliotecare"
  },
  {
    "id": 829,
    "ipa": "bijutErie",
    "hint": "名词 · 复数待核对: bijuterii"
  },
  {
    "id": 830,
    "ipa": "blândEțe",
    "hint": "名词 · 复数待核对: blândeți"
  },
  {
    "id": 831,
    "ipa": "bOAbe",
    "hint": "名词 · 复数待核对: boabi"
  },
  {
    "id": 832,
    "ipa": "bOnus",
    "hint": "名词 · 复数待核对: bonuse"
  },
  {
    "id": 833,
    "ipa": "bucătAr",
    "hint": "名词 · 复数待核对: bucătare"
  },
  {
    "id": 834,
    "ipa": "bUmbac",
    "hint": "名词 · 复数待核对: bumbace"
  },
  {
    "id": 835,
    "ipa": "burIc",
    "hint": "名词 · 复数待核对: burice"
  },
  {
    "id": 836,
    "ipa": "bUrsier",
    "hint": "名词 · 复数待核对: bursiere"
  },
  {
    "id": 837,
    "ipa": "cafEInă",
    "hint": "名词 · 复数: cafeine"
  },
  {
    "id": 838,
    "ipa": "campIOnat",
    "hint": "名词 · 复数待核对: campionate"
  },
  {
    "id": 839,
    "ipa": "candIdat",
    "hint": "名词 · 复数待核对: candidate"
  },
  {
    "id": 840,
    "ipa": "canApea",
    "hint": "名词 · 复数待核对: canapeai"
  },
  {
    "id": 841,
    "ipa": "cantitAte",
    "hint": "名词 · 复数: cantități"
  },
  {
    "id": 842,
    "ipa": "caracteristIcă",
    "hint": "名词 · 复数: caracteristice"
  },
  {
    "id": 843,
    "ipa": "cAsier",
    "hint": "名词 · 复数待核对: casiere"
  },
  {
    "id": 844,
    "ipa": "ceainIc",
    "hint": "名词 · 复数待核对: ceainice"
  },
  {
    "id": 845,
    "ipa": "celUlă",
    "hint": "名词 · 复数: celule"
  },
  {
    "id": 846,
    "ipa": "centUră",
    "hint": "名词 · 复数: centure"
  },
  {
    "id": 847,
    "ipa": "cercetAre",
    "hint": "名词 · 复数待核对: cercetari"
  },
  {
    "id": 848,
    "ipa": "cernEAlă",
    "hint": "名词 · 复数待核对: cerneli"
  },
  {
    "id": 849,
    "ipa": "chEIE",
    "hint": "名词 · 复数待核对: cheii"
  },
  {
    "id": 850,
    "ipa": "chitArist",
    "hint": "名词 · 复数待核对: chitariste"
  },
  {
    "id": 851,
    "ipa": "chitAnță",
    "hint": "名词 · 复数: chitanțe"
  },
  {
    "id": 852,
    "ipa": "chestionAr",
    "hint": "名词 · 复数待核对: chestionare"
  },
  {
    "id": 853,
    "ipa": "chIrurg",
    "hint": "名词 · 复数待核对: chirurge"
  },
  {
    "id": 854,
    "ipa": "cIfră",
    "hint": "名词 · 复数: cifre"
  },
  {
    "id": 855,
    "ipa": "cInste",
    "hint": "名词 · 复数待核对: cinsti"
  },
  {
    "id": 856,
    "ipa": "cirEAșă",
    "hint": "名词 · 复数: cireașe"
  },
  {
    "id": 857,
    "ipa": "citItor",
    "hint": "名词 · 复数待核对: cititoare"
  },
  {
    "id": 858,
    "ipa": "coafOr",
    "hint": "名词 · 复数待核对: coafore"
  },
  {
    "id": 859,
    "ipa": "cOApsă",
    "hint": "名词 · 复数: coapse"
  },
  {
    "id": 860,
    "ipa": "coborÂre",
    "hint": "名词 · 复数待核对: coborâri"
  },
  {
    "id": 861,
    "ipa": "cOd",
    "hint": "名词 · 复数待核对: code"
  },
  {
    "id": 862,
    "ipa": "colaborAre",
    "hint": "名词 · 复数待核对: colaborari"
  },
  {
    "id": 863,
    "ipa": "cOlet",
    "hint": "名词 · 复数待核对: colete"
  },
  {
    "id": 864,
    "ipa": "colOAnă",
    "hint": "名词 · 复数: coloane"
  },
  {
    "id": 865,
    "ipa": "combustIbil",
    "hint": "名词 · 复数待核对: combustibile"
  },
  {
    "id": 866,
    "ipa": "comIsie",
    "hint": "名词 · 复数待核对: comisii"
  },
  {
    "id": 867,
    "ipa": "compasIUne",
    "hint": "名词 · 复数: compasiuni"
  },
  {
    "id": 868,
    "ipa": "competEnt",
    "hint": "形容词 · f: competentă · pl: competenți/ente"
  },
  {
    "id": 869,
    "ipa": "comunitAte",
    "hint": "名词 · 复数: comunități"
  },
  {
    "id": 870,
    "ipa": "cOncert",
    "hint": "名词 · 复数待核对: concerte"
  },
  {
    "id": 871,
    "ipa": "cOncurs",
    "hint": "名词 · 复数待核对: concurse"
  },
  {
    "id": 872,
    "ipa": "condIție",
    "hint": "名词 · 复数: condiții"
  },
  {
    "id": 873,
    "ipa": "cOnflict",
    "hint": "名词 · 复数待核对: conflicte"
  },
  {
    "id": 874,
    "ipa": "cOnfort",
    "hint": "名词 · 复数待核对: conforte"
  },
  {
    "id": 875,
    "ipa": "consimțĂmânt",
    "hint": "名词 · 复数待核对: consimțământe"
  },
  {
    "id": 876,
    "ipa": "constrUcție",
    "hint": "名词 · 复数: construcții"
  },
  {
    "id": 877,
    "ipa": "consultAnt",
    "hint": "名词 · 复数待核对: consultați"
  },
  {
    "id": 878,
    "ipa": "cOnsum",
    "hint": "名词 · 复数待核对: consume"
  },
  {
    "id": 879,
    "ipa": "cOntact",
    "hint": "名词 · 复数待核对: contacte"
  },
  {
    "id": 880,
    "ipa": "copilĂrie",
    "hint": "名词 · 复数待核对: copilării"
  },
  {
    "id": 881,
    "ipa": "corUpție",
    "hint": "名词 · 复数: corupții"
  },
  {
    "id": 882,
    "ipa": "cravAtă",
    "hint": "名词 · 复数: cravate"
  },
  {
    "id": 883,
    "ipa": "crEmă",
    "hint": "名词 · 复数: creme"
  },
  {
    "id": 884,
    "ipa": "crEșă",
    "hint": "名词 · 复数: creșe"
  },
  {
    "id": 885,
    "ipa": "critEriu",
    "hint": "名词 · 复数待核对: criterii"
  },
  {
    "id": 886,
    "ipa": "crOItor",
    "hint": "名词 · 复数待核对: croitoare"
  },
  {
    "id": 887,
    "ipa": "cUb",
    "hint": "名词 · 复数待核对: cube"
  },
  {
    "id": 888,
    "ipa": "cunoștInțe",
    "hint": "名词 · 复数待核对: cunoștinți"
  },
  {
    "id": 889,
    "ipa": "curățEnie",
    "hint": "名词 · 复数待核对: curățenii"
  },
  {
    "id": 890,
    "ipa": "curiozitAte",
    "hint": "名词 · 复数: curiozități"
  },
  {
    "id": 891,
    "ipa": "cursAnt",
    "hint": "名词 · 复数待核对: cursați"
  },
  {
    "id": 892,
    "ipa": "cutrEmur",
    "hint": "名词 · 复数待核对: cutremure"
  },
  {
    "id": 893,
    "ipa": "dEbit",
    "hint": "名词 · 复数待核对: debite"
  },
  {
    "id": 894,
    "ipa": "dEfect",
    "hint": "名词 · 复数待核对: defecte"
  },
  {
    "id": 895,
    "ipa": "delEgat",
    "hint": "名词 · 复数待核对: delegate"
  },
  {
    "id": 896,
    "ipa": "demnitAte",
    "hint": "名词 · 复数: demnități"
  },
  {
    "id": 897,
    "ipa": "depOzit",
    "hint": "名词 · 复数待核对: depozite"
  },
  {
    "id": 898,
    "ipa": "dEsert",
    "hint": "名词 · 复数待核对: deserte"
  },
  {
    "id": 899,
    "ipa": "destinAție",
    "hint": "名词 · 复数: destinații"
  },
  {
    "id": 900,
    "ipa": "detectIv",
    "hint": "名词 · 复数待核对: detective"
  },
  {
    "id": 901,
    "ipa": "dezAstru",
    "hint": "名词 · 复数待核对: dezastruri"
  },
  {
    "id": 902,
    "ipa": "dezbatEre",
    "hint": "名词 · 复数待核对: dezbateri"
  },
  {
    "id": 903,
    "ipa": "dezvoltAre",
    "hint": "名词 · 复数待核对: dezvoltari"
  },
  {
    "id": 904,
    "ipa": "diagnostIc",
    "hint": "名词 · 复数待核对: diagnostice"
  },
  {
    "id": 905,
    "ipa": "difuzOr",
    "hint": "名词 · 复数待核对: difuzore"
  },
  {
    "id": 906,
    "ipa": "disciplInă",
    "hint": "名词 · 复数: discipline"
  },
  {
    "id": 907,
    "ipa": "dispozitIv",
    "hint": "名词 · 复数待核对: dispozitive"
  },
  {
    "id": 908,
    "ipa": "diversitAte",
    "hint": "名词 · 复数: diversități"
  },
  {
    "id": 909,
    "ipa": "dobÂndă",
    "hint": "名词 · 复数: dobânde"
  },
  {
    "id": 910,
    "ipa": "domEniu",
    "hint": "名词 · 复数待核对: domenii"
  },
  {
    "id": 911,
    "ipa": "donAție",
    "hint": "名词 · 复数: donații"
  },
  {
    "id": 912,
    "ipa": "dorInță",
    "hint": "名词 · 复数: dorințe"
  },
  {
    "id": 913,
    "ipa": "dOvleac",
    "hint": "名词 · 复数待核对: dovleace"
  },
  {
    "id": 914,
    "ipa": "dreptAte",
    "hint": "名词 · 复数: dreptăți"
  },
  {
    "id": 915,
    "ipa": "dUș",
    "hint": "名词 · 复数待核对: dușe"
  },
  {
    "id": 916,
    "ipa": "duzInă",
    "hint": "名词 · 复数: duzine"
  },
  {
    "id": 917,
    "ipa": "Ecou",
    "hint": "名词 · 复数待核对: ecouri"
  },
  {
    "id": 918,
    "ipa": "editUră",
    "hint": "名词 · 复数: editure"
  },
  {
    "id": 919,
    "ipa": "educAtor",
    "hint": "名词 · 复数待核对: educatoare"
  },
  {
    "id": 920,
    "ipa": "eficIEnță",
    "hint": "名词 · 复数: eficiențe"
  },
  {
    "id": 921,
    "ipa": "egalitAte",
    "hint": "名词 · 复数: egalități"
  },
  {
    "id": 922,
    "ipa": "echIpaj",
    "hint": "名词 · 复数待核对: echipaje"
  },
  {
    "id": 923,
    "ipa": "echipAment",
    "hint": "名词 · 复数: echipamente"
  },
  {
    "id": 924,
    "ipa": "Ecran",
    "hint": "名词 · 复数待核对: ecrane"
  },
  {
    "id": 925,
    "ipa": "edItor",
    "hint": "名词 · 复数待核对: editoare"
  },
  {
    "id": 926,
    "ipa": "emoționAl",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 927,
    "ipa": "entUziasm",
    "hint": "名词 · 复数待核对: entuziasme"
  },
  {
    "id": 928,
    "ipa": "epIsod",
    "hint": "名词 · 复数待核对: episode"
  },
  {
    "id": 929,
    "ipa": "esEnță",
    "hint": "名词 · 复数: esențe"
  },
  {
    "id": 930,
    "ipa": "etApă",
    "hint": "名词 · 复数: etape"
  },
  {
    "id": 931,
    "ipa": "evidEnță",
    "hint": "名词 · 复数: evidențe"
  },
  {
    "id": 932,
    "ipa": "excEpție",
    "hint": "名词 · 复数: excepții"
  },
  {
    "id": 933,
    "ipa": "exercIțiu",
    "hint": "名词 · 复数待核对: exerciții"
  },
  {
    "id": 934,
    "ipa": "exigEnță",
    "hint": "名词 · 复数: exigențe"
  },
  {
    "id": 935,
    "ipa": "expedIEre",
    "hint": "名词 · 复数待核对: expedieri"
  },
  {
    "id": 936,
    "ipa": "Expert",
    "hint": "名词 · 复数待核对: experte"
  },
  {
    "id": 937,
    "ipa": "fAIAnță",
    "hint": "名词 · 复数: faianțe"
  },
  {
    "id": 938,
    "ipa": "farmAcist",
    "hint": "名词 · 复数待核对: farmaciste"
  },
  {
    "id": 939,
    "ipa": "favOAre",
    "hint": "名词 · 复数待核对: favoari"
  },
  {
    "id": 940,
    "ipa": "fEbră",
    "hint": "名词 · 复数: febre"
  },
  {
    "id": 941,
    "ipa": "fermOAr",
    "hint": "名词 · 复数待核对: fermoare"
  },
  {
    "id": 942,
    "ipa": "fiabilitAte",
    "hint": "名词 · 复数: fiabilități"
  },
  {
    "id": 943,
    "ipa": "fIbra",
    "hint": "名词 · 复数待核对: fibrai"
  },
  {
    "id": 944,
    "ipa": "ficțIUne",
    "hint": "名词 · 复数: ficțiuni"
  },
  {
    "id": 945,
    "ipa": "fIltru",
    "hint": "名词 · 复数待核对: filtruri"
  },
  {
    "id": 946,
    "ipa": "finanțAre",
    "hint": "名词 · 复数待核对: finanțari"
  },
  {
    "id": 947,
    "ipa": "fIrmă",
    "hint": "名词 · 复数: firme"
  },
  {
    "id": 948,
    "ipa": "flutUre",
    "hint": "名词 · 复数待核对: fluturi"
  },
  {
    "id": 949,
    "ipa": "fOAIE",
    "hint": "名词 · 复数待核对: foaii"
  },
  {
    "id": 950,
    "ipa": "folOs",
    "hint": "名词 · 复数待核对: folose"
  },
  {
    "id": 951,
    "ipa": "fOrță",
    "hint": "名词 · 复数: forțe"
  },
  {
    "id": 952,
    "ipa": "frÂnă",
    "hint": "名词 · 复数: frâne"
  },
  {
    "id": 953,
    "ipa": "frecvEnță",
    "hint": "名词 · 复数: frecvențe"
  },
  {
    "id": 954,
    "ipa": "frOnt",
    "hint": "名词 · 复数待核对: fronte"
  },
  {
    "id": 955,
    "ipa": "frUct",
    "hint": "名词 · 复数待核对: fructe"
  },
  {
    "id": 956,
    "ipa": "fUm",
    "hint": "名词 · 复数待核对: fume"
  },
  {
    "id": 957,
    "ipa": "fundAl",
    "hint": "名词 · 复数待核对: fundale"
  },
  {
    "id": 958,
    "ipa": "fUrt",
    "hint": "名词 · 复数待核对: furte"
  },
  {
    "id": 959,
    "ipa": "gAj",
    "hint": "名词 · 复数待核对: gaje"
  },
  {
    "id": 960,
    "ipa": "gArd",
    "hint": "名词 · 复数待核对: garde"
  },
  {
    "id": 961,
    "ipa": "gAzdă",
    "hint": "名词 · 复数: gazde"
  },
  {
    "id": 962,
    "ipa": "generAție",
    "hint": "名词 · 复数: generații"
  },
  {
    "id": 963,
    "ipa": "geogrAfie",
    "hint": "名词 · 复数待核对: geografii"
  },
  {
    "id": 964,
    "ipa": "geolOgie",
    "hint": "名词 · 复数待核对: geologii"
  },
  {
    "id": 965,
    "ipa": "gestionAre",
    "hint": "名词 · 复数待核对: gestionari"
  },
  {
    "id": 966,
    "ipa": "ghicitOAre",
    "hint": "名词 · 复数待核对: ghicitoari"
  },
  {
    "id": 967,
    "ipa": "ghIșeu",
    "hint": "名词 · 复数待核对: ghișeuri"
  },
  {
    "id": 968,
    "ipa": "glOrie",
    "hint": "名词 · 复数待核对: glorii"
  },
  {
    "id": 969,
    "ipa": "gOl",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 970,
    "ipa": "gospodĂrie",
    "hint": "名词 · 复数待核对: gospodării"
  },
  {
    "id": 971,
    "ipa": "grAd",
    "hint": "名词 · 复数待核对: grade"
  },
  {
    "id": 972,
    "ipa": "grafIc",
    "hint": "名词 · 复数待核对: grafice"
  },
  {
    "id": 973,
    "ipa": "granIță",
    "hint": "名词 · 复数: granițe"
  },
  {
    "id": 974,
    "ipa": "grăsIme",
    "hint": "名词 · 复数待核对: grăsimi"
  },
  {
    "id": 975,
    "ipa": "grÂU",
    "hint": "名词 · 复数待核对: grâuri"
  },
  {
    "id": 976,
    "ipa": "greșEAlă",
    "hint": "名词 · 复数待核对: greșeli"
  },
  {
    "id": 977,
    "ipa": "gustAre",
    "hint": "名词 · 复数待核对: gustari"
  },
  {
    "id": 978,
    "ipa": "hAlat",
    "hint": "名词 · 复数待核对: halate"
  },
  {
    "id": 979,
    "ipa": "hrAnă",
    "hint": "名词 · 复数: hrane"
  },
  {
    "id": 980,
    "ipa": "identitAte",
    "hint": "名词 · 复数: identități"
  },
  {
    "id": 981,
    "ipa": "igIEnă",
    "hint": "名词 · 复数: igiene"
  },
  {
    "id": 982,
    "ipa": "ilustrAție",
    "hint": "名词 · 复数: ilustrații"
  },
  {
    "id": 983,
    "ipa": "impOzit",
    "hint": "名词 · 复数待核对: impozite"
  },
  {
    "id": 984,
    "ipa": "incidEnt",
    "hint": "名词 · 复数待核对: incidente"
  },
  {
    "id": 985,
    "ipa": "indIciu",
    "hint": "名词 · 复数待核对: indicii"
  },
  {
    "id": 986,
    "ipa": "inflAție",
    "hint": "名词 · 复数: inflații"
  },
  {
    "id": 987,
    "ipa": "inițiatIvă",
    "hint": "名词 · 复数: inițiative"
  },
  {
    "id": 988,
    "ipa": "injEcție",
    "hint": "名词 · 复数: injecții"
  },
  {
    "id": 989,
    "ipa": "inovAție",
    "hint": "名词 · 复数: inovații"
  },
  {
    "id": 990,
    "ipa": "instAnță",
    "hint": "名词 · 复数: instanțe"
  },
  {
    "id": 991,
    "ipa": "institUție",
    "hint": "名词 · 复数: instituții"
  },
  {
    "id": 992,
    "ipa": "inteligEnță",
    "hint": "名词 · 复数: inteligențe"
  },
  {
    "id": 993,
    "ipa": "interdIcție",
    "hint": "名词 · 复数: interdicții"
  },
  {
    "id": 994,
    "ipa": "interfAță",
    "hint": "名词 · 复数: interfațe"
  },
  {
    "id": 995,
    "ipa": "intErpret",
    "hint": "名词 · 复数待核对: interprete"
  },
  {
    "id": 996,
    "ipa": "intimitAte",
    "hint": "名词 · 复数: intimități"
  },
  {
    "id": 997,
    "ipa": "ipotEză",
    "hint": "名词 · 复数: ipoteze"
  },
  {
    "id": 998,
    "ipa": "istOrie",
    "hint": "名词 · 复数待核对: istorii"
  },
  {
    "id": 999,
    "ipa": "izolAre",
    "hint": "名词 · 复数待核对: izolari"
  },
  {
    "id": 1000,
    "ipa": "împrUmut",
    "hint": "名词 · 复数待核对: împrumute"
  },
  {
    "id": 1001,
    "ipa": "încălzIre",
    "hint": "名词 · 复数待核对: încălziri"
  },
  {
    "id": 1002,
    "ipa": "încredEre",
    "hint": "名词 · 复数待核对: încrederi"
  },
  {
    "id": 1003,
    "ipa": "îndemânAre",
    "hint": "名词 · 复数待核对: îndemânari"
  },
  {
    "id": 1004,
    "ipa": "întârzIEre",
    "hint": "名词 · 复数待核对: întârzieri"
  },
  {
    "id": 1005,
    "ipa": "întreținEre",
    "hint": "名词 · 复数待核对: întrețineri"
  },
  {
    "id": 1006,
    "ipa": "jAle",
    "hint": "名词 · 复数待核对: jali"
  },
  {
    "id": 1007,
    "ipa": "jalUzea",
    "hint": "名词 · 复数待核对: jaluzeai"
  },
  {
    "id": 1008,
    "ipa": "jAr",
    "hint": "名词 · 复数待核对: jare"
  },
  {
    "id": 1009,
    "ipa": "jEAns",
    "hint": "名词 · 复数待核对: jeanse"
  },
  {
    "id": 1010,
    "ipa": "jurĂmânt",
    "hint": "名词 · 复数待核对: jurământe"
  },
  {
    "id": 1011,
    "ipa": "justIție",
    "hint": "名词 · 复数: justiții"
  },
  {
    "id": 1012,
    "ipa": "kilomEtraj",
    "hint": "名词 · 复数待核对: kilometraje"
  },
  {
    "id": 1013,
    "ipa": "laborAnt",
    "hint": "名词 · 复数待核对: laborați"
  },
  {
    "id": 1014,
    "ipa": "lAcăt",
    "hint": "名词 · 复数待核对: lacăte"
  },
  {
    "id": 1015,
    "ipa": "lapovIță",
    "hint": "名词 · 复数: lapovițe"
  },
  {
    "id": 1016,
    "ipa": "legislAție",
    "hint": "名词 · 复数: legislații"
  },
  {
    "id": 1017,
    "ipa": "lezIUne",
    "hint": "名词 · 复数: leziuni"
  },
  {
    "id": 1018,
    "ipa": "licitAție",
    "hint": "名词 · 复数: licitații"
  },
  {
    "id": 1019,
    "ipa": "lIder",
    "hint": "名词 · 复数待核对: lidere"
  },
  {
    "id": 1020,
    "ipa": "lImbaj",
    "hint": "名词 · 复数待核对: limbaje"
  },
  {
    "id": 1021,
    "ipa": "lIchid",
    "hint": "名词 · 复数待核对: lichide"
  },
  {
    "id": 1022,
    "ipa": "livrAre",
    "hint": "名词 · 复数待核对: livrari"
  },
  {
    "id": 1023,
    "ipa": "logIcă",
    "hint": "名词 · 复数: logice"
  },
  {
    "id": 1024,
    "ipa": "loialitAte",
    "hint": "名词 · 复数: loialități"
  },
  {
    "id": 1025,
    "ipa": "lotErie",
    "hint": "名词 · 复数待核对: loterii"
  },
  {
    "id": 1026,
    "ipa": "macAra",
    "hint": "名词 · 复数待核对: macarai"
  },
  {
    "id": 1027,
    "ipa": "mAgnet",
    "hint": "名词 · 复数待核对: magnete"
  },
  {
    "id": 1028,
    "ipa": "majoritAte",
    "hint": "名词 · 复数: majorități"
  },
  {
    "id": 1029,
    "ipa": "mAndat",
    "hint": "名词 · 复数待核对: mandate"
  },
  {
    "id": 1030,
    "ipa": "manEvră",
    "hint": "名词 · 复数: manevre"
  },
  {
    "id": 1031,
    "ipa": "mArfă",
    "hint": "名词 · 复数: marfe"
  },
  {
    "id": 1032,
    "ipa": "mArjă",
    "hint": "名词 · 复数: marje"
  },
  {
    "id": 1033,
    "ipa": "mărtUrie",
    "hint": "名词 · 复数待核对: mărturii"
  },
  {
    "id": 1034,
    "ipa": "mătAse",
    "hint": "名词 · 复数待核对: mătasi"
  },
  {
    "id": 1035,
    "ipa": "medicAment",
    "hint": "名词 · 复数: medicamente"
  },
  {
    "id": 1036,
    "ipa": "memOrie",
    "hint": "名词 · 复数待核对: memorii"
  },
  {
    "id": 1037,
    "ipa": "mEnaj",
    "hint": "名词 · 复数待核对: menaje"
  },
  {
    "id": 1038,
    "ipa": "mentenAnță",
    "hint": "名词 · 复数: mentenanțe"
  },
  {
    "id": 1039,
    "ipa": "mercenAr",
    "hint": "名词 · 复数待核对: mercenare"
  },
  {
    "id": 1040,
    "ipa": "mErit",
    "hint": "名词 · 复数待核对: merite"
  },
  {
    "id": 1041,
    "ipa": "mEsaj",
    "hint": "名词 · 复数待核对: mesaje"
  },
  {
    "id": 1042,
    "ipa": "meștEșug",
    "hint": "名词 · 复数待核对: meșteșuge"
  },
  {
    "id": 1043,
    "ipa": "mEtrou",
    "hint": "名词 · 复数待核对: metrouri"
  },
  {
    "id": 1044,
    "ipa": "micrOfon",
    "hint": "名词 · 复数待核对: microfone"
  },
  {
    "id": 1045,
    "ipa": "migrAție",
    "hint": "名词 · 复数: migrații"
  },
  {
    "id": 1046,
    "ipa": "milIOAne",
    "hint": "名词 · 复数待核对: milioani"
  },
  {
    "id": 1047,
    "ipa": "mincIUnă",
    "hint": "名词 · 复数: minciune"
  },
  {
    "id": 1048,
    "ipa": "mIner",
    "hint": "名词 · 复数待核对: minere"
  },
  {
    "id": 1049,
    "ipa": "mirAcol",
    "hint": "名词 · 复数待核对: miracole"
  },
  {
    "id": 1050,
    "ipa": "misIUne",
    "hint": "名词 · 复数: misiuni"
  },
  {
    "id": 1051,
    "ipa": "mizErie",
    "hint": "名词 · 复数待核对: mizerii"
  },
  {
    "id": 1052,
    "ipa": "mobIlier",
    "hint": "名词 · 复数待核对: mobiliere"
  },
  {
    "id": 1053,
    "ipa": "moștenIre",
    "hint": "名词 · 复数待核对: moșteniri"
  },
  {
    "id": 1054,
    "ipa": "motivAre",
    "hint": "名词 · 复数待核对: motivari"
  },
  {
    "id": 1055,
    "ipa": "mulțIme",
    "hint": "名词 · 复数待核对: mulțimi"
  },
  {
    "id": 1056,
    "ipa": "narațIUne",
    "hint": "名词 · 复数: narațiuni"
  },
  {
    "id": 1057,
    "ipa": "națIUne",
    "hint": "名词 · 复数: națiuni"
  },
  {
    "id": 1058,
    "ipa": "negocIEre",
    "hint": "名词 · 复数待核对: negocieri"
  },
  {
    "id": 1059,
    "ipa": "nErv",
    "hint": "名词 · 复数待核对: nerve"
  },
  {
    "id": 1060,
    "ipa": "notificAre",
    "hint": "名词 · 复数待核对: notificari"
  },
  {
    "id": 1061,
    "ipa": "nUAnță",
    "hint": "名词 · 复数: nuanțe"
  },
  {
    "id": 1062,
    "ipa": "obiectIv",
    "hint": "名词 · 复数待核对: obiective"
  },
  {
    "id": 1063,
    "ipa": "obligAție",
    "hint": "名词 · 复数: obligații"
  },
  {
    "id": 1064,
    "ipa": "observAție",
    "hint": "名词 · 复数: observații"
  },
  {
    "id": 1065,
    "ipa": "ochelAri",
    "hint": "名词 · 复数待核对: ochelarii"
  },
  {
    "id": 1066,
    "ipa": "oficIAl",
    "hint": "名词 · 复数待核对: oficiale"
  },
  {
    "id": 1067,
    "ipa": "oglindIre",
    "hint": "名词 · 复数待核对: oglindiri"
  },
  {
    "id": 1068,
    "ipa": "operAtor",
    "hint": "名词 · 复数待核对: operatoare"
  },
  {
    "id": 1069,
    "ipa": "opțIUne",
    "hint": "名词 · 复数: opțiuni"
  },
  {
    "id": 1070,
    "ipa": "orĂșel",
    "hint": "名词 · 复数待核对: orășele"
  },
  {
    "id": 1071,
    "ipa": "origIne",
    "hint": "名词 · 复数待核对: origini"
  },
  {
    "id": 1072,
    "ipa": "ospitalitAte",
    "hint": "名词 · 复数: ospitalități"
  },
  {
    "id": 1073,
    "ipa": "otrAvă",
    "hint": "名词 · 复数: otrave"
  },
  {
    "id": 1074,
    "ipa": "pÂIne",
    "hint": "名词 · 复数待核对: pâini"
  },
  {
    "id": 1075,
    "ipa": "pAlat",
    "hint": "名词 · 复数待核对: palate"
  },
  {
    "id": 1076,
    "ipa": "pAlton",
    "hint": "名词 · 复数待核对: paltone"
  },
  {
    "id": 1077,
    "ipa": "pAnou",
    "hint": "名词 · 复数待核对: panouri"
  },
  {
    "id": 1078,
    "ipa": "parAgraf",
    "hint": "名词 · 复数待核对: paragrafe"
  },
  {
    "id": 1079,
    "ipa": "pArfum",
    "hint": "名词 · 复数待核对: parfume"
  },
  {
    "id": 1080,
    "ipa": "partEner",
    "hint": "名词 · 复数待核对: partenere"
  },
  {
    "id": 1081,
    "ipa": "pAs",
    "hint": "名词 · 复数待核对: pase"
  },
  {
    "id": 1082,
    "ipa": "patrimOniu",
    "hint": "名词 · 复数待核对: patrimonii"
  },
  {
    "id": 1083,
    "ipa": "pAUză",
    "hint": "名词 · 复数: pauze"
  },
  {
    "id": 1084,
    "ipa": "pavIlion",
    "hint": "名词 · 复数待核对: pavilione"
  },
  {
    "id": 1085,
    "ipa": "pErdea",
    "hint": "名词 · 复数待核对: perdeai"
  },
  {
    "id": 1086,
    "ipa": "performAnță",
    "hint": "名词 · 复数: performanțe"
  },
  {
    "id": 1087,
    "ipa": "perifErie",
    "hint": "名词 · 复数待核对: periferii"
  },
  {
    "id": 1088,
    "ipa": "permIsie",
    "hint": "名词 · 复数待核对: permisii"
  },
  {
    "id": 1089,
    "ipa": "perspectIvă",
    "hint": "名词 · 复数: perspective"
  },
  {
    "id": 1090,
    "ipa": "pescAr",
    "hint": "名词 · 复数待核对: pescare"
  },
  {
    "id": 1091,
    "ipa": "petAlă",
    "hint": "名词 · 复数: petale"
  },
  {
    "id": 1092,
    "ipa": "pIAță",
    "hint": "名词 · 复数: piațe"
  },
  {
    "id": 1093,
    "ipa": "pIEton",
    "hint": "名词 · 复数待核对: pietone"
  },
  {
    "id": 1094,
    "ipa": "pilOți",
    "hint": "名词 · 复数待核对: piloții"
  },
  {
    "id": 1095,
    "ipa": "plIc",
    "hint": "名词 · 复数待核对: plice"
  },
  {
    "id": 1096,
    "ipa": "plOAIE",
    "hint": "名词 · 复数待核对: ploaii"
  },
  {
    "id": 1097,
    "ipa": "pOd",
    "hint": "名词 · 复数待核对: pode"
  },
  {
    "id": 1098,
    "ipa": "polIțist",
    "hint": "名词 · 复数待核对: polițiste"
  },
  {
    "id": 1099,
    "ipa": "pOmpier",
    "hint": "名词 · 复数待核对: pompiere"
  },
  {
    "id": 1100,
    "ipa": "populAție",
    "hint": "名词 · 复数: populații"
  },
  {
    "id": 1101,
    "ipa": "pOrție",
    "hint": "名词 · 复数: porții"
  },
  {
    "id": 1102,
    "ipa": "pOrt",
    "hint": "名词 · 复数待核对: porte"
  },
  {
    "id": 1103,
    "ipa": "portocAlă",
    "hint": "名词 · 复数: portocale"
  },
  {
    "id": 1104,
    "ipa": "pozIție",
    "hint": "名词 · 复数: poziții"
  },
  {
    "id": 1105,
    "ipa": "prietEnie",
    "hint": "名词 · 复数待核对: prietenii"
  },
  {
    "id": 1106,
    "ipa": "prObă",
    "hint": "名词 · 复数: probe"
  },
  {
    "id": 1107,
    "ipa": "procedUră",
    "hint": "名词 · 复数: procedure"
  },
  {
    "id": 1108,
    "ipa": "prOces",
    "hint": "名词 · 复数待核对: procese"
  },
  {
    "id": 1109,
    "ipa": "producĂtor",
    "hint": "名词 · 复数待核对: producătoare"
  },
  {
    "id": 1110,
    "ipa": "profesOr",
    "hint": "名词 · 复数待核对: profesore"
  },
  {
    "id": 1111,
    "ipa": "prOfit",
    "hint": "名词 · 复数待核对: profite"
  },
  {
    "id": 1112,
    "ipa": "promisIUne",
    "hint": "名词 · 复数: promisiuni"
  },
  {
    "id": 1113,
    "ipa": "propunEre",
    "hint": "名词 · 复数待核对: propuneri"
  },
  {
    "id": 1114,
    "ipa": "prOsop",
    "hint": "名词 · 复数待核对: prosope"
  },
  {
    "id": 1115,
    "ipa": "publIc",
    "hint": "名词 · 复数待核对: publice"
  },
  {
    "id": 1116,
    "ipa": "pulOver",
    "hint": "名词 · 复数待核对: pulovere"
  },
  {
    "id": 1117,
    "ipa": "rachEtă",
    "hint": "名词 · 复数: rachete"
  },
  {
    "id": 1118,
    "ipa": "radAr",
    "hint": "名词 · 复数待核对: radare"
  },
  {
    "id": 1119,
    "ipa": "rafinAment",
    "hint": "名词 · 复数: rafinamente"
  },
  {
    "id": 1120,
    "ipa": "ramUră",
    "hint": "名词 · 复数: ramure"
  },
  {
    "id": 1121,
    "ipa": "rAtă",
    "hint": "名词 · 复数: rate"
  },
  {
    "id": 1122,
    "ipa": "răcEAlă",
    "hint": "名词 · 复数待核对: răceli"
  },
  {
    "id": 1123,
    "ipa": "recEnzie",
    "hint": "名词 · 复数待核对: recenzii"
  },
  {
    "id": 1124,
    "ipa": "reciprocitAte",
    "hint": "名词 · 复数: reciprocități"
  },
  {
    "id": 1125,
    "ipa": "recompEnsă",
    "hint": "名词 · 复数: recompense"
  },
  {
    "id": 1126,
    "ipa": "recrutAre",
    "hint": "名词 · 复数待核对: recrutari"
  },
  {
    "id": 1127,
    "ipa": "rEfuz",
    "hint": "名词 · 复数待核对: refuze"
  },
  {
    "id": 1128,
    "ipa": "regizOr",
    "hint": "名词 · 复数待核对: regizore"
  },
  {
    "id": 1129,
    "ipa": "rEgret",
    "hint": "名词 · 复数待核对: regrete"
  },
  {
    "id": 1130,
    "ipa": "rețEtă",
    "hint": "名词 · 复数: rețete"
  },
  {
    "id": 1131,
    "ipa": "rezervOr",
    "hint": "名词 · 复数待核对: rezervore"
  },
  {
    "id": 1132,
    "ipa": "rezistEnță",
    "hint": "名词 · 复数: rezistențe"
  },
  {
    "id": 1133,
    "ipa": "rObust",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1134,
    "ipa": "rUcsac",
    "hint": "名词 · 复数待核对: rucsace"
  },
  {
    "id": 1135,
    "ipa": "salAriu",
    "hint": "名词 · 复数待核对: salarii"
  },
  {
    "id": 1136,
    "ipa": "sĂpun",
    "hint": "名词 · 复数待核对: săpune"
  },
  {
    "id": 1137,
    "ipa": "scandAl",
    "hint": "名词 · 复数待核对: scandale"
  },
  {
    "id": 1138,
    "ipa": "scAră",
    "hint": "名词 · 复数: scare"
  },
  {
    "id": 1139,
    "ipa": "sceptIc",
    "hint": "形容词 · f: sceptică · pl: sceptici/ice"
  },
  {
    "id": 1140,
    "ipa": "schIță",
    "hint": "名词 · 复数: schițe"
  },
  {
    "id": 1141,
    "ipa": "scrIItor",
    "hint": "名词 · 复数待核对: scriitoare"
  },
  {
    "id": 1142,
    "ipa": "scurtătUră",
    "hint": "名词 · 复数: scurtăture"
  },
  {
    "id": 1143,
    "ipa": "sEcol",
    "hint": "副词 · 不变"
  },
  {
    "id": 1144,
    "ipa": "senAtor",
    "hint": "名词 · 复数待核对: senatoare"
  },
  {
    "id": 1145,
    "ipa": "servIEtă",
    "hint": "名词 · 复数: serviete"
  },
  {
    "id": 1146,
    "ipa": "sesIUne",
    "hint": "名词 · 复数: sesiuni"
  },
  {
    "id": 1147,
    "ipa": "sEver",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1148,
    "ipa": "sfÂrșit",
    "hint": "副词 · 不变"
  },
  {
    "id": 1149,
    "ipa": "sigIliu",
    "hint": "名词 · 复数待核对: sigilii"
  },
  {
    "id": 1150,
    "ipa": "silUEtă",
    "hint": "名词 · 复数: siluete"
  },
  {
    "id": 1151,
    "ipa": "sIndrom",
    "hint": "名词 · 复数待核对: sindrome"
  },
  {
    "id": 1152,
    "ipa": "singurătAte",
    "hint": "名词 · 复数: singurătăți"
  },
  {
    "id": 1153,
    "ipa": "sintEză",
    "hint": "名词 · 复数: sinteze"
  },
  {
    "id": 1154,
    "ipa": "sirEnă",
    "hint": "名词 · 复数: sirene"
  },
  {
    "id": 1155,
    "ipa": "slăbicIUne",
    "hint": "名词 · 复数: slăbiciuni"
  },
  {
    "id": 1156,
    "ipa": "slUjbă",
    "hint": "名词 · 复数: slujbe"
  },
  {
    "id": 1157,
    "ipa": "sOl",
    "hint": "名词 · 复数待核对: sole"
  },
  {
    "id": 1158,
    "ipa": "sOld",
    "hint": "名词 · 复数待核对: solde"
  },
  {
    "id": 1159,
    "ipa": "sOndaj",
    "hint": "名词 · 复数待核对: sondaje"
  },
  {
    "id": 1160,
    "ipa": "spAțiu",
    "hint": "名词 · 复数待核对: spații"
  },
  {
    "id": 1161,
    "ipa": "spAte",
    "hint": "名词 · 复数待核对: spati"
  },
  {
    "id": 1162,
    "ipa": "specIAlist",
    "hint": "名词 · 复数待核对: specialiste"
  },
  {
    "id": 1163,
    "ipa": "spectAcol",
    "hint": "名词 · 复数待核对: spectacole"
  },
  {
    "id": 1164,
    "ipa": "spitalizAre",
    "hint": "名词 · 复数待核对: spitalizari"
  },
  {
    "id": 1165,
    "ipa": "stratEgie",
    "hint": "名词 · 复数待核对: strategii"
  },
  {
    "id": 1166,
    "ipa": "strEs",
    "hint": "名词 · 复数待核对: strese"
  },
  {
    "id": 1167,
    "ipa": "sUbiect",
    "hint": "名词 · 复数待核对: subiecte"
  },
  {
    "id": 1168,
    "ipa": "sUbsol",
    "hint": "名词 · 复数待核对: subsole"
  },
  {
    "id": 1169,
    "ipa": "suferInță",
    "hint": "名词 · 复数: suferințe"
  },
  {
    "id": 1170,
    "ipa": "sugEstie",
    "hint": "名词 · 复数待核对: sugestii"
  },
  {
    "id": 1171,
    "ipa": "supraveghEre",
    "hint": "名词 · 复数待核对: supravegheri"
  },
  {
    "id": 1172,
    "ipa": "sUrâs",
    "hint": "名词 · 复数待核对: surâse"
  },
  {
    "id": 1173,
    "ipa": "sUrub",
    "hint": "名词 · 复数待核对: surube"
  },
  {
    "id": 1174,
    "ipa": "susținEre",
    "hint": "名词 · 复数待核对: susțineri"
  },
  {
    "id": 1175,
    "ipa": "șAnsă",
    "hint": "名词 · 复数: șanse"
  },
  {
    "id": 1176,
    "ipa": "ședInță",
    "hint": "名词 · 复数: ședințe"
  },
  {
    "id": 1177,
    "ipa": "șervEțel",
    "hint": "名词 · 复数待核对: șervețele"
  },
  {
    "id": 1178,
    "ipa": "șOfer",
    "hint": "名词 · 复数待核对: șofere"
  },
  {
    "id": 1179,
    "ipa": "tabĂră",
    "hint": "名词 · 复数: tabăre"
  },
  {
    "id": 1180,
    "ipa": "tactIcă",
    "hint": "名词 · 复数: tactice"
  },
  {
    "id": 1181,
    "ipa": "talEnt",
    "hint": "名词 · 复数待核对: talente"
  },
  {
    "id": 1182,
    "ipa": "tAvan",
    "hint": "名词 · 复数待核对: tavane"
  },
  {
    "id": 1183,
    "ipa": "tăietUră",
    "hint": "名词 · 复数: tăieture"
  },
  {
    "id": 1184,
    "ipa": "tĂrie",
    "hint": "名词 · 复数待核对: tării"
  },
  {
    "id": 1185,
    "ipa": "tEAnc",
    "hint": "名词 · 复数待核对: teance"
  },
  {
    "id": 1186,
    "ipa": "tencUIAlă",
    "hint": "名词 · 复数: tencuiale"
  },
  {
    "id": 1187,
    "ipa": "tEOrie",
    "hint": "名词 · 复数待核对: teorii"
  },
  {
    "id": 1188,
    "ipa": "terApie",
    "hint": "名词 · 复数待核对: terapii"
  },
  {
    "id": 1189,
    "ipa": "tErmen",
    "hint": "名词 · 复数待核对: termene"
  },
  {
    "id": 1190,
    "ipa": "terOrism",
    "hint": "名词 · 复数待核对: terorisme"
  },
  {
    "id": 1191,
    "ipa": "tEzaur",
    "hint": "名词 · 复数待核对: tezaure"
  },
  {
    "id": 1192,
    "ipa": "tIchet",
    "hint": "名词 · 复数待核对: tichete"
  },
  {
    "id": 1193,
    "ipa": "tIgru",
    "hint": "名词 · 复数待核对: tigruri"
  },
  {
    "id": 1194,
    "ipa": "tipAr",
    "hint": "名词 · 复数待核对: tipare"
  },
  {
    "id": 1195,
    "ipa": "tIraj",
    "hint": "名词 · 复数待核对: tiraje"
  },
  {
    "id": 1196,
    "ipa": "tocAnă",
    "hint": "名词 · 复数: tocane"
  },
  {
    "id": 1197,
    "ipa": "tombEron",
    "hint": "名词 · 复数待核对: tomberone"
  },
  {
    "id": 1198,
    "ipa": "trAI",
    "hint": "名词 · 复数待核对: traii"
  },
  {
    "id": 1199,
    "ipa": "trAseu",
    "hint": "名词 · 复数待核对: traseuri"
  },
  {
    "id": 1200,
    "ipa": "trAtat",
    "hint": "名词 · 复数待核对: tratate"
  },
  {
    "id": 1201,
    "ipa": "tribUnă",
    "hint": "名词 · 复数: tribune"
  },
  {
    "id": 1202,
    "ipa": "trUc",
    "hint": "名词 · 复数待核对: truce"
  },
  {
    "id": 1203,
    "ipa": "trUp",
    "hint": "名词 · 复数待核对: trupe"
  },
  {
    "id": 1204,
    "ipa": "tUnel",
    "hint": "名词 · 复数待核对: tunele"
  },
  {
    "id": 1205,
    "ipa": "tUrmă",
    "hint": "名词 · 复数: turme"
  },
  {
    "id": 1206,
    "ipa": "ucenIc",
    "hint": "名词 · 复数待核对: ucenice"
  },
  {
    "id": 1207,
    "ipa": "Ulei",
    "hint": "名词 · 复数待核对: uleii"
  },
  {
    "id": 1208,
    "ipa": "Umbră",
    "hint": "名词 · 复数: umbre"
  },
  {
    "id": 1209,
    "ipa": "umilInță",
    "hint": "名词 · 复数: umilințe"
  },
  {
    "id": 1210,
    "ipa": "Unchi",
    "hint": "名词 · 复数待核对: unchii"
  },
  {
    "id": 1211,
    "ipa": "unifOrmă",
    "hint": "名词 · 复数: uniforme"
  },
  {
    "id": 1212,
    "ipa": "urgEnță",
    "hint": "名词 · 复数: urgențe"
  },
  {
    "id": 1213,
    "ipa": "ustUroi",
    "hint": "名词 · 复数待核对: usturoii"
  },
  {
    "id": 1214,
    "ipa": "utilitAte",
    "hint": "名词 · 复数: utilități"
  },
  {
    "id": 1215,
    "ipa": "vAgon",
    "hint": "名词 · 复数待核对: vagone"
  },
  {
    "id": 1216,
    "ipa": "valIză",
    "hint": "名词 · 复数: valize"
  },
  {
    "id": 1217,
    "ipa": "vapOr",
    "hint": "名词 · 复数待核对: vapore"
  },
  {
    "id": 1218,
    "ipa": "vArză",
    "hint": "名词 · 复数: varze"
  },
  {
    "id": 1219,
    "ipa": "vÂrstă",
    "hint": "名词 · 复数: vârste"
  },
  {
    "id": 1220,
    "ipa": "vÂnt",
    "hint": "名词 · 复数待核对: vânte"
  },
  {
    "id": 1221,
    "ipa": "vErdict",
    "hint": "名词 · 复数待核对: verdicte"
  },
  {
    "id": 1222,
    "ipa": "vEstă",
    "hint": "名词 · 复数: veste"
  },
  {
    "id": 1223,
    "ipa": "veșnIcie",
    "hint": "名词 · 复数待核对: veșnicii"
  },
  {
    "id": 1224,
    "ipa": "victImă",
    "hint": "名词 · 复数: victime"
  },
  {
    "id": 1225,
    "ipa": "vidEOclip",
    "hint": "名词 · 复数待核对: videoclipe"
  },
  {
    "id": 1226,
    "ipa": "vigilEnt",
    "hint": "形容词 · f: vigilentă · pl: vigilenți/ente"
  },
  {
    "id": 1227,
    "ipa": "vIItor",
    "hint": "副词 · 不变"
  },
  {
    "id": 1228,
    "ipa": "violEnță",
    "hint": "名词 · 复数: violențe"
  },
  {
    "id": 1229,
    "ipa": "vIOAră",
    "hint": "名词 · 复数: vioare"
  },
  {
    "id": 1230,
    "ipa": "vizibilitAte",
    "hint": "名词 · 复数: vizibilități"
  },
  {
    "id": 1231,
    "ipa": "vocabulAr",
    "hint": "名词 · 复数待核对: vocabulare"
  },
  {
    "id": 1232,
    "ipa": "vOInță",
    "hint": "名词 · 复数: voințe"
  },
  {
    "id": 1233,
    "ipa": "vOlan",
    "hint": "名词 · 复数待核对: volane"
  },
  {
    "id": 1234,
    "ipa": "vOlum",
    "hint": "名词 · 复数待核对: volume"
  },
  {
    "id": 1235,
    "ipa": "vrEme",
    "hint": "名词 · 复数待核对: vremi"
  },
  {
    "id": 1236,
    "ipa": "zAr",
    "hint": "名词 · 复数待核对: zare"
  },
  {
    "id": 1237,
    "ipa": "zbOr",
    "hint": "名词 · 复数待核对: zbore"
  },
  {
    "id": 1238,
    "ipa": "zEstre",
    "hint": "名词 · 复数待核对: zestri"
  },
  {
    "id": 1239,
    "ipa": "zIAr",
    "hint": "名词 · 复数待核对: ziare"
  },
  {
    "id": 1240,
    "ipa": "zId",
    "hint": "名词 · 复数待核对: zide"
  },
  {
    "id": 1241,
    "ipa": "zmEUră",
    "hint": "名词 · 复数: zmeure"
  },
  {
    "id": 1242,
    "ipa": "absOlut",
    "hint": "形容词 · f: absolută · pl: absoluți/ute"
  },
  {
    "id": 1243,
    "ipa": "absolUtă",
    "hint": "形容词 · m/f 待核对 · pl: absolute"
  },
  {
    "id": 1244,
    "ipa": "accesIbil",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1245,
    "ipa": "actIv",
    "hint": "形容词 · f: activă · pl: activi/ive"
  },
  {
    "id": 1246,
    "ipa": "actIvă",
    "hint": "形容词 · m/f 待核对 · pl: active"
  },
  {
    "id": 1247,
    "ipa": "agresIv",
    "hint": "形容词 · f: agresivă · pl: agresivi/ive"
  },
  {
    "id": 1248,
    "ipa": "agresIvă",
    "hint": "形容词 · m/f 待核对 · pl: agresive"
  },
  {
    "id": 1249,
    "ipa": "amAr",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1250,
    "ipa": "amAră",
    "hint": "形容词 · m/f 待核对 · pl: amare"
  },
  {
    "id": 1251,
    "ipa": "amAbil",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1252,
    "ipa": "Amplu",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1253,
    "ipa": "aprOpiat",
    "hint": "形容词 · f: apropiată · pl: apropiați/ate"
  },
  {
    "id": 1254,
    "ipa": "apropIAtă",
    "hint": "形容词 · m/f 待核对 · pl: apropiate"
  },
  {
    "id": 1255,
    "ipa": "ascUțit",
    "hint": "形容词 · f: ascuțită · pl: ascuțiți/ite"
  },
  {
    "id": 1256,
    "ipa": "ascuțItă",
    "hint": "形容词 · m/f 待核对 · pl: ascuțite"
  },
  {
    "id": 1257,
    "ipa": "atEnt",
    "hint": "形容词 · f: atentă · pl: atenți/ente"
  },
  {
    "id": 1258,
    "ipa": "atractIv",
    "hint": "形容词 · f: atractivă · pl: atractivi/ive"
  },
  {
    "id": 1259,
    "ipa": "atractIvă",
    "hint": "形容词 · m/f 待核对 · pl: atractive"
  },
  {
    "id": 1260,
    "ipa": "bOgat",
    "hint": "形容词 · f: bogată · pl: bogați/ate"
  },
  {
    "id": 1261,
    "ipa": "bogAtă",
    "hint": "形容词 · m/f 待核对 · pl: bogate"
  },
  {
    "id": 1262,
    "ipa": "cAld",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1263,
    "ipa": "centrAl",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1264,
    "ipa": "centrAlă",
    "hint": "形容词 · m/f 待核对 · pl: centrale"
  },
  {
    "id": 1265,
    "ipa": "clAr",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1266,
    "ipa": "clAră",
    "hint": "形容词 · m/f 待核对 · pl: clare"
  },
  {
    "id": 1267,
    "ipa": "cOmod",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1268,
    "ipa": "cOmplet",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1269,
    "ipa": "cOmun",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1270,
    "ipa": "cOncret",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1271,
    "ipa": "cUrat",
    "hint": "形容词 · f: curată · pl: curați/ate"
  },
  {
    "id": 1272,
    "ipa": "curAtă",
    "hint": "形容词 · m/f 待核对 · pl: curate"
  },
  {
    "id": 1273,
    "ipa": "curIOs",
    "hint": "形容词 · f: curioasă · pl: curioși/oase"
  },
  {
    "id": 1274,
    "ipa": "curIOAsă",
    "hint": "形容词 · m/f 待核对 · pl: curioase"
  },
  {
    "id": 1275,
    "ipa": "delicIOs",
    "hint": "形容词 · f: delicioasă · pl: delicioși/oase"
  },
  {
    "id": 1276,
    "ipa": "delicIOAsă",
    "hint": "形容词 · m/f 待核对 · pl: delicioase"
  },
  {
    "id": 1277,
    "ipa": "dEschis",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1278,
    "ipa": "difIcil",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1279,
    "ipa": "dIrect",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1280,
    "ipa": "disponIbil",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1281,
    "ipa": "eficIEnt",
    "hint": "形容词 · f: eficientă · pl: eficienți/ente"
  },
  {
    "id": 1282,
    "ipa": "egAl",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1283,
    "ipa": "egAlă",
    "hint": "形容词 · m/f 待核对 · pl: egale"
  },
  {
    "id": 1284,
    "ipa": "elegAnt",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1285,
    "ipa": "Enorm",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1286,
    "ipa": "Exact",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1287,
    "ipa": "excelEnt",
    "hint": "形容词 · f: excelentă · pl: excelenți/ente"
  },
  {
    "id": 1288,
    "ipa": "fAls",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1289,
    "ipa": "familIAr",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1290,
    "ipa": "familIAră",
    "hint": "形容词 · m/f 待核对 · pl: familiare"
  },
  {
    "id": 1291,
    "ipa": "ferIcit",
    "hint": "形容词 · f: fericită · pl: fericiți/ite"
  },
  {
    "id": 1292,
    "ipa": "fericItă",
    "hint": "形容词 · m/f 待核对 · pl: fericite"
  },
  {
    "id": 1293,
    "ipa": "flexIbil",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1294,
    "ipa": "frAged",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1295,
    "ipa": "frumOs",
    "hint": "形容词 · f: frumoasă · pl: frumoși/oase"
  },
  {
    "id": 1296,
    "ipa": "frumOAsă",
    "hint": "形容词 · m/f 待核对 · pl: frumoase"
  },
  {
    "id": 1297,
    "ipa": "generOs",
    "hint": "形容词 · f: generoasă · pl: generoși/oase"
  },
  {
    "id": 1298,
    "ipa": "generOAsă",
    "hint": "形容词 · m/f 待核对 · pl: generoase"
  },
  {
    "id": 1299,
    "ipa": "grEU",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1300,
    "ipa": "IEftin",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1301,
    "ipa": "imEdiat",
    "hint": "形容词 · f: imediată · pl: imediați/ate"
  },
  {
    "id": 1302,
    "ipa": "imedIAtă",
    "hint": "形容词 · m/f 待核对 · pl: imediate"
  },
  {
    "id": 1303,
    "ipa": "independEnt",
    "hint": "形容词 · f: independentă · pl: independenți/ente"
  },
  {
    "id": 1304,
    "ipa": "Intens",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1305,
    "ipa": "linIștit",
    "hint": "形容词 · f: liniștită · pl: liniștiți/ite"
  },
  {
    "id": 1306,
    "ipa": "liniștItă",
    "hint": "形容词 · m/f 待核对 · pl: liniștite"
  },
  {
    "id": 1307,
    "ipa": "locAl",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1308,
    "ipa": "locAlă",
    "hint": "形容词 · m/f 待核对 · pl: locale"
  },
  {
    "id": 1309,
    "ipa": "lUng",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1310,
    "ipa": "mAtur",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1311,
    "ipa": "mOAle",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1312,
    "ipa": "naturAl",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1313,
    "ipa": "naturAlă",
    "hint": "形容词 · m/f 待核对 · pl: naturale"
  },
  {
    "id": 1314,
    "ipa": "necesAr",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1315,
    "ipa": "necesAră",
    "hint": "形容词 · m/f 待核对 · pl: necesare"
  },
  {
    "id": 1316,
    "ipa": "normAl",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1317,
    "ipa": "normAlă",
    "hint": "形容词 · m/f 待核对 · pl: normale"
  },
  {
    "id": 1318,
    "ipa": "nOU",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1319,
    "ipa": "oficIAlă",
    "hint": "形容词 · m/f 待核对 · pl: oficiale"
  },
  {
    "id": 1320,
    "ipa": "optImist",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1321,
    "ipa": "ordOnat",
    "hint": "形容词 · f: ordonată · pl: ordonați/ate"
  },
  {
    "id": 1322,
    "ipa": "ordonAtă",
    "hint": "形容词 · m/f 待核对 · pl: ordonate"
  },
  {
    "id": 1323,
    "ipa": "originAl",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1324,
    "ipa": "originAlă",
    "hint": "形容词 · m/f 待核对 · pl: originale"
  },
  {
    "id": 1325,
    "ipa": "permanEnt",
    "hint": "形容词 · f: permanentă · pl: permanenți/ente"
  },
  {
    "id": 1326,
    "ipa": "personAl",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1327,
    "ipa": "personAlă",
    "hint": "形容词 · m/f 待核对 · pl: personale"
  },
  {
    "id": 1328,
    "ipa": "plĂcut",
    "hint": "形容词 · f: plăcută · pl: plăcuți/ute"
  },
  {
    "id": 1329,
    "ipa": "plăcUtă",
    "hint": "形容词 · m/f 待核对 · pl: plăcute"
  },
  {
    "id": 1330,
    "ipa": "populAr",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1331,
    "ipa": "populAră",
    "hint": "形容词 · m/f 待核对 · pl: populare"
  },
  {
    "id": 1332,
    "ipa": "pozitIv",
    "hint": "形容词 · f: pozitivă · pl: pozitivi/ive"
  },
  {
    "id": 1333,
    "ipa": "pozitIvă",
    "hint": "形容词 · m/f 待核对 · pl: pozitive"
  },
  {
    "id": 1334,
    "ipa": "practIc",
    "hint": "形容词 · f: practică · pl: practici/ice"
  },
  {
    "id": 1335,
    "ipa": "practIcă",
    "hint": "形容词 · m/f 待核对 · pl: practice"
  },
  {
    "id": 1336,
    "ipa": "prEcis",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1337,
    "ipa": "prOfund",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1338,
    "ipa": "rApid",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1339,
    "ipa": "rAr",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1340,
    "ipa": "rAră",
    "hint": "形容词 · m/f 待核对 · pl: rare"
  },
  {
    "id": 1341,
    "ipa": "recEnt",
    "hint": "形容词 · f: recentă · pl: recenți/ente"
  },
  {
    "id": 1342,
    "ipa": "rezistEnt",
    "hint": "形容词 · f: rezistentă · pl: rezistenți/ente"
  },
  {
    "id": 1343,
    "ipa": "rOtund",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1344,
    "ipa": "sănătOs",
    "hint": "形容词 · f: sănătoasă · pl: sănătoși/oase"
  },
  {
    "id": 1345,
    "ipa": "sănătOAsă",
    "hint": "形容词 · m/f 待核对 · pl: sănătoase"
  },
  {
    "id": 1346,
    "ipa": "scUrt",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1347,
    "ipa": "sensIbil",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1348,
    "ipa": "serIOs",
    "hint": "形容词 · f: serioasă · pl: serioși/oase"
  },
  {
    "id": 1349,
    "ipa": "serIOAsă",
    "hint": "形容词 · m/f 待核对 · pl: serioase"
  },
  {
    "id": 1350,
    "ipa": "sIncer",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1351,
    "ipa": "sIngur",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1352,
    "ipa": "specIAl",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1353,
    "ipa": "specIAlă",
    "hint": "形容词 · m/f 待核对 · pl: speciale"
  },
  {
    "id": 1354,
    "ipa": "stAbil",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1355,
    "ipa": "subțIre",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1356,
    "ipa": "suficIEnt",
    "hint": "形容词 · f: suficientă · pl: suficienți/ente"
  },
  {
    "id": 1357,
    "ipa": "sUrprins",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1358,
    "ipa": "tehnIc",
    "hint": "形容词 · f: tehnică · pl: tehnici/ice"
  },
  {
    "id": 1359,
    "ipa": "tehnIcă",
    "hint": "形容词 · m/f 待核对 · pl: tehnice"
  },
  {
    "id": 1360,
    "ipa": "trIst",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1361,
    "ipa": "ușOr",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1362,
    "ipa": "Util",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1363,
    "ipa": "vEsel",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1364,
    "ipa": "vizIbil",
    "hint": "形容词 · 形式待核对"
  },
  {
    "id": 1365,
    "ipa": "accEpta",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1366,
    "ipa": "accEptat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1367,
    "ipa": "admIra",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1368,
    "ipa": "admIrat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1369,
    "ipa": "adUce",
    "hint": "动词 · -e 类"
  },
  {
    "id": 1370,
    "ipa": "Afla",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1371,
    "ipa": "Aflat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1372,
    "ipa": "ajUnge",
    "hint": "动词 · -e 类"
  },
  {
    "id": 1373,
    "ipa": "alEge",
    "hint": "动词 · -e 类"
  },
  {
    "id": 1374,
    "ipa": "apĂrea",
    "hint": "动词 · -ea 类"
  },
  {
    "id": 1375,
    "ipa": "aprInde",
    "hint": "动词 · -e 类"
  },
  {
    "id": 1376,
    "ipa": "arĂta",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1377,
    "ipa": "arĂtat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1378,
    "ipa": "arUnca",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1379,
    "ipa": "arUncat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1380,
    "ipa": "ascUlta",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1381,
    "ipa": "ascUltat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1382,
    "ipa": "aștEpta",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1383,
    "ipa": "aștEptat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1384,
    "ipa": "atInge",
    "hint": "动词 · -e 类"
  },
  {
    "id": 1385,
    "ipa": "AUzi",
    "hint": "动词 · -esc 变位"
  },
  {
    "id": 1386,
    "ipa": "AUzit",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1387,
    "ipa": "bEA",
    "hint": "动词 · -ea 类"
  },
  {
    "id": 1388,
    "ipa": "câștIga",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1389,
    "ipa": "câștIgat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1390,
    "ipa": "cEre",
    "hint": "动词 · -e 类"
  },
  {
    "id": 1391,
    "ipa": "chEma",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1392,
    "ipa": "chEmat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1393,
    "ipa": "chEltui",
    "hint": "动词 · -esc 变位"
  },
  {
    "id": 1394,
    "ipa": "chEltuit",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1395,
    "ipa": "circUla",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1396,
    "ipa": "circUlat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1397,
    "ipa": "cIti",
    "hint": "动词 · -esc 变位"
  },
  {
    "id": 1398,
    "ipa": "cItit",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1399,
    "ipa": "cobOrî",
    "hint": "动词 · -ăsc 变位"
  },
  {
    "id": 1400,
    "ipa": "cobOrit",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1401,
    "ipa": "comAnda",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1402,
    "ipa": "comAndat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1403,
    "ipa": "complEta",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1404,
    "ipa": "complEtat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1405,
    "ipa": "cumpĂra",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1406,
    "ipa": "cumpĂrat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1407,
    "ipa": "cunOAște",
    "hint": "动词 · -e 类"
  },
  {
    "id": 1408,
    "ipa": "curĂța",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1409,
    "ipa": "curĂțat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1410,
    "ipa": "deschIde",
    "hint": "动词 · -e 类"
  },
  {
    "id": 1411,
    "ipa": "desEna",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1412,
    "ipa": "desEnat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1413,
    "ipa": "discUta",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1414,
    "ipa": "discUtat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1415,
    "ipa": "dOrmi",
    "hint": "动词 · -esc 变位"
  },
  {
    "id": 1416,
    "ipa": "dOrmit",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1417,
    "ipa": "expEdia",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1418,
    "ipa": "expEdiat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1419,
    "ipa": "explIca",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1420,
    "ipa": "explIcat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1421,
    "ipa": "fAce",
    "hint": "动词 · -e 类"
  },
  {
    "id": 1422,
    "ipa": "fotogrAfia",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1423,
    "ipa": "fotogrAfiat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1424,
    "ipa": "gĂsi",
    "hint": "动词 · -esc 变位"
  },
  {
    "id": 1425,
    "ipa": "gĂsit",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1426,
    "ipa": "gĂti",
    "hint": "动词 · -esc 变位"
  },
  {
    "id": 1427,
    "ipa": "gĂtit",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1428,
    "ipa": "glUmi",
    "hint": "动词 · -esc 变位"
  },
  {
    "id": 1429,
    "ipa": "glUmit",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1430,
    "ipa": "grEși",
    "hint": "动词 · -esc 变位"
  },
  {
    "id": 1431,
    "ipa": "grEșit",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1432,
    "ipa": "învĂța",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1433,
    "ipa": "învĂțat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1434,
    "ipa": "închIde",
    "hint": "动词 · -e 类"
  },
  {
    "id": 1435,
    "ipa": "încEpe",
    "hint": "动词 · -e 类"
  },
  {
    "id": 1436,
    "ipa": "încErca",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1437,
    "ipa": "încErcat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1438,
    "ipa": "înțelEge",
    "hint": "动词 · -e 类"
  },
  {
    "id": 1439,
    "ipa": "întrEba",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1440,
    "ipa": "întrEbat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1441,
    "ipa": "Intra",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1442,
    "ipa": "Intrat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1443,
    "ipa": "IEși",
    "hint": "动词 · -esc 变位"
  },
  {
    "id": 1444,
    "ipa": "IEșit",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1445,
    "ipa": "IUbi",
    "hint": "动词 · -esc 变位"
  },
  {
    "id": 1446,
    "ipa": "IUbit",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1447,
    "ipa": "jUca",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1448,
    "ipa": "jUcat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1449,
    "ipa": "lOcui",
    "hint": "动词 · -esc 变位"
  },
  {
    "id": 1450,
    "ipa": "lOcuit",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1451,
    "ipa": "lUcra",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1452,
    "ipa": "lUcrat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1453,
    "ipa": "lUA",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1454,
    "ipa": "lUAt",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1455,
    "ipa": "mÂnca",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1456,
    "ipa": "mÂncat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1457,
    "ipa": "mErge",
    "hint": "动词 · -e 类"
  },
  {
    "id": 1458,
    "ipa": "mUta",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1459,
    "ipa": "mUtat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1460,
    "ipa": "nOta",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1461,
    "ipa": "nOtat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1462,
    "ipa": "obsErva",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1463,
    "ipa": "obsErvat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1464,
    "ipa": "organIza",
    "hint": "动词 · -ez 变位"
  },
  {
    "id": 1465,
    "ipa": "organIzat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1466,
    "ipa": "pArca",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1467,
    "ipa": "pArcat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1468,
    "ipa": "particIpa",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1469,
    "ipa": "particIpat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1470,
    "ipa": "plĂti",
    "hint": "动词 · -esc 变位"
  },
  {
    "id": 1471,
    "ipa": "plĂtit",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1472,
    "ipa": "plEca",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1473,
    "ipa": "plEcat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1474,
    "ipa": "prImi",
    "hint": "动词 · -esc 变位"
  },
  {
    "id": 1475,
    "ipa": "prImit",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1476,
    "ipa": "pronUnța",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1477,
    "ipa": "pronUnțat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1478,
    "ipa": "protEja",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1479,
    "ipa": "protEjat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1480,
    "ipa": "publIca",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1481,
    "ipa": "publIcat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1482,
    "ipa": "pUrta",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1483,
    "ipa": "pUrtat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1484,
    "ipa": "repAra",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1485,
    "ipa": "repArat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1486,
    "ipa": "repEta",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1487,
    "ipa": "repEtat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1488,
    "ipa": "rezOlva",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1489,
    "ipa": "rezOlvat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1490,
    "ipa": "răspUnde",
    "hint": "动词 · -e 类"
  },
  {
    "id": 1491,
    "ipa": "rămÂne",
    "hint": "动词 · -e 类"
  },
  {
    "id": 1492,
    "ipa": "sAlva",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1493,
    "ipa": "sAlvat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1494,
    "ipa": "schImba",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1495,
    "ipa": "schImbat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1496,
    "ipa": "scrIE",
    "hint": "动词 · -e 类"
  },
  {
    "id": 1497,
    "ipa": "sEmna",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1498,
    "ipa": "sEmnat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1499,
    "ipa": "sImți",
    "hint": "动词 · -esc 变位"
  },
  {
    "id": 1500,
    "ipa": "sImțit",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1501,
    "ipa": "spĂla",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1502,
    "ipa": "spĂlat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1503,
    "ipa": "spUne",
    "hint": "动词 · -e 类"
  },
  {
    "id": 1504,
    "ipa": "stA",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1505,
    "ipa": "stUdia",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1506,
    "ipa": "stUdiat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1507,
    "ipa": "trimIte",
    "hint": "动词 · -e 类"
  },
  {
    "id": 1508,
    "ipa": "UIta",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1509,
    "ipa": "UItat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1510,
    "ipa": "Urca",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1511,
    "ipa": "Urcat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1512,
    "ipa": "urmĂri",
    "hint": "动词 · -esc 变位"
  },
  {
    "id": 1513,
    "ipa": "urmĂrit",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1514,
    "ipa": "verifIca",
    "hint": "动词 · -ez 变位"
  },
  {
    "id": 1515,
    "ipa": "verifIcat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1516,
    "ipa": "vInde",
    "hint": "动词 · -e 类"
  },
  {
    "id": 1517,
    "ipa": "vizIta",
    "hint": "动词 · 零变位"
  },
  {
    "id": 1518,
    "ipa": "vizItat",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1519,
    "ipa": "vOrbi",
    "hint": "动词 · -esc 变位"
  },
  {
    "id": 1520,
    "ipa": "vOrbit",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1521,
    "ipa": "zÂmbi",
    "hint": "动词 · -esc 变位"
  },
  {
    "id": 1522,
    "ipa": "zÂmbit",
    "hint": "动词 · 变位待核对"
  },
  {
    "id": 1523,
    "ipa": "acAsă",
    "hint": "副词 · 不变"
  },
  {
    "id": 1524,
    "ipa": "afAră",
    "hint": "副词 · 不变"
  },
  {
    "id": 1525,
    "ipa": "aprOApe",
    "hint": "副词 · 不变"
  },
  {
    "id": 1526,
    "ipa": "Azi",
    "hint": "副词 · 不变"
  },
  {
    "id": 1527,
    "ipa": "bIne",
    "hint": "副词 · 不变"
  },
  {
    "id": 1528,
    "ipa": "cUrând",
    "hint": "副词 · 不变"
  },
  {
    "id": 1529,
    "ipa": "depArte",
    "hint": "副词 · 不变"
  },
  {
    "id": 1530,
    "ipa": "dEs",
    "hint": "副词 · 不变"
  },
  {
    "id": 1531,
    "ipa": "devrEme",
    "hint": "副词 · 不变"
  },
  {
    "id": 1532,
    "ipa": "IEri",
    "hint": "副词 · 不变"
  },
  {
    "id": 1533,
    "ipa": "împrEUnă",
    "hint": "副词 · 不变"
  },
  {
    "id": 1534,
    "ipa": "înApoi",
    "hint": "副词 · 不变"
  },
  {
    "id": 1535,
    "ipa": "înAInte",
    "hint": "副词 · 不变"
  },
  {
    "id": 1536,
    "ipa": "Încet",
    "hint": "副词 · 不变"
  },
  {
    "id": 1537,
    "ipa": "mEreu",
    "hint": "副词 · 不变"
  },
  {
    "id": 1538,
    "ipa": "mÂIne",
    "hint": "副词 · 不变"
  },
  {
    "id": 1539,
    "ipa": "niciodAtă",
    "hint": "副词 · 不变"
  },
  {
    "id": 1540,
    "ipa": "repEde",
    "hint": "副词 · 不变"
  },
  {
    "id": 1541,
    "ipa": "tÂrziu",
    "hint": "副词 · 不变"
  },
  {
    "id": 1542,
    "ipa": "totUși",
    "hint": "副词 · 不变"
  }
];
