const seeds = `
abecedar|字母课本|学习
absolvent|毕业生|教育
academie|学院|教育
acces|入口|城市
accident|事故|交通
acord|同意|人际
activitate|活动|日常
acum|现在|时间
adânc|深的|形容词
adult|成年人|人际
aer|空气|自然
afacere|生意|商业
agendă|日程本|职场
ajutor|帮助|人际
alarmă|警报|城市
aliment|食品|饮食
ambulanță|救护车|健康
amintire|回忆|人际
analiză|分析|学习
ananas|菠萝|饮食
apartament|公寓|家居
apetit|食欲|健康
aprilie|四月|时间
argint|银|购物
armată|军队|社会
aromă|香味|饮食
ascensor|电梯|城市
asistent|助手|职场
atac|攻击|社会
atenție|注意|学习
august|八月|时间
autor|作者|艺术
autostradă|高速路|交通
avans|预付款|金融
avantaj|优势|职场
avertizare|警告|社会
baghetă|长棍面包|饮食
balcon|阳台|家居
balenă|鲸鱼|自然
barcă|小船|交通
baterie|电池|科技
băiat|男孩|人际
bătrân|老人|人际
bibliografie|参考书目|学习
bilet|票|交通
birou|办公桌|职场
biscuit|饼干|饮食
bloc|楼房|家居
boală|疾病|健康
bomboană|糖果|饮食
bord|仪表盘|交通
brățară|手链|购物
brutărie|面包店|城市
bucurie|快乐|情感
buletin|身份证|社会
buton|按钮|科技
cabană|小木屋|旅行
cadă|浴缸|家居
caiet|笔记本|学习
calendar|日历|时间
calitate|质量|购物
campanie|活动|社会
canal|频道|科技
capac|盖子|家居
caracter|性格|人际
carieră|职业|职场
cartier|街区|城市
castravete|黄瓜|饮食
catalog|目录|学习
cazier|犯罪记录|社会
căldură|热|天气
cămin|宿舍|教育
cântar|秤|购物
cârnat|香肠|饮食
ceapă|洋葱|饮食
ceas|钟表|时间
cerere|申请|职场
certificat|证书|教育
cheltuială|开销|金融
chirie|房租|家居
ciorbă|酸汤|饮食
ciupercă|蘑菇|饮食
clădire|建筑|城市
coadă|队伍|购物
coajă|皮|饮食
cofetărie|甜品店|城市
colegiu|学院|教育
colind|圣诞歌|文化
comandă|订单|购物
comerț|贸易|商业
companie|公司|职场
competiție|竞赛|运动
comportament|行为|人际
concluzie|结论|学习
conducere|管理|职场
conferință|会议|职场
consiliu|委员会|社会
contor|计量表|家居
conținut|内容|科技
copertă|封面|学习
coridor|走廊|城市
costum|西装|购物
cratiță|锅|烹饪
creier|大脑|身体
creștere|增长|商业
criză|危机|社会
cuier|衣架|家居
cultură|文化|文化
curaj|勇气|情感
curent|电流|科技
curte|院子|家居
cutie|盒子|购物
datorie|债务|金融
decembrie|十二月|时间
decizie|决定|职场
declarație|声明|社会
deget|手指|身体
dejun|午餐|饮食
demisol|半地下室|家居
desen|画|艺术
detaliu|细节|学习
dezavantaj|劣势|职场
dialog|对话|学习
diferență|区别|学习
dimineață|早晨|时间
director|主任|职场
discuție|讨论|人际
distanță|距离|交通
distribuție|分配|商业
dovadă|证据|社会
dulap|柜子|家居
duminică|星期日|时间
echilibru|平衡|健康
economie|经济|金融
efort|努力|学习
emoție|情绪|情感
energie|能量|健康
eroare|错误|学习
etaj|楼层|城市
etichetă|标签|购物
eveniment|事件|社会
exemplu|例子|学习
experiență|经验|职场
explicație|解释|学习
familie|家庭|人际
februarie|二月|时间
felicitare|贺卡|人际
fericire|幸福|情感
festival|节日|文化
fișier|文件|科技
flacără|火焰|自然
formular|表格|职场
fotoliu|扶手椅|家居
frig|寒冷|天气
friptură|烤肉|饮食
funcție|功能|科技
garanție|保修|购物
găleată|桶|家居
gând|想法|情感
geamantan|行李箱|旅行
gem|果酱|饮食
genunchi|膝盖|身体
gest|手势|人际
gheață|冰|饮食
ghid|指南|旅行
ghiozdan|书包|学习
glumă|玩笑|人际
grădină|花园|自然
greutate|重量|健康
grijă|关心|情感
grup|小组|学习
gust|味道|饮食
haină|外套|购物
hârtie|纸|学习
hartă|地图|旅行
hotărâre|决心|情感
idee|想法|学习
ieșire|出口|城市
imagine|图片|艺术
impact|影响|社会
impresie|印象|人际
incendiu|火灾|城市
industrie|工业|商业
informație|信息|学习
ingredient|食材|烹饪
inspector|检查员|职场
instrucțiune|说明|科技
instrument|工具|职场
intenție|意图|人际
interes|兴趣|情感
invitație|邀请|人际
ianuarie|一月|时间
iunie|六月|时间
iulie|七月|时间
izvor|泉水|自然
jachetă|夹克|购物
joi|星期四|时间
jucărie|玩具|购物
judecător|法官|社会
laborator|实验室|教育
lanț|链子|购物
legătură|联系|人际
lemn|木头|自然
lenjerie|床上用品|家居
libertate|自由|社会
linie|线|学习
linguriță|小勺|烹饪
listă|清单|学习
locuință|住宅|家居
lucrător|工人|职场
luni|星期一|时间
lumină|光|家居
magazin|商店|购物
maioneză|蛋黄酱|饮食
manager|经理|职场
martie|三月|时间
marți|星期二|时间
mașină|汽车|交通
măsură|措施|社会
medalie|奖牌|运动
mediu|环境|自然
membru|成员|人际
meniu|菜单|饮食
meserie|职业|职场
metodă|方法|学习
miercuri|星期三|时间
mijloc|中间|方向
minoritate|少数群体|社会
minut|分钟|时间
miros|气味|饮食
model|模型|学习
monitor|显示器|科技
morcov|胡萝卜|饮食
motiv|理由|人际
mușchi|肌肉|身体
naștere|出生|人际
nepot|侄子|人际
nivel|水平|学习
noiembrie|十一月|时间
nor|云|天气
notă|分数|教育
obicei|习惯|日常
obiect|物品|日常
oboseală|疲劳|健康
ocazie|机会|人际
octombrie|十月|时间
ofertă|优惠|购物
oglindă|镜子|家居
opinie|意见|人际
ordine|秩序|社会
organizație|组织|社会
orizont|地平线|自然
ospătar|服务员|饮食
pachet|包裹|购物
pagină|页面|学习
parcare|停车场|交通
participant|参与者|社会
pasager|乘客|交通
pastă|酱|饮食
pălărie|帽子|购物
părere|看法|人际
pătură|毯子|家居
perete|墙|家居
pericol|危险|社会
perioadă|时期|时间
permis|许可证|社会
pescuit|钓鱼|运动
piept|胸部|身体
pilot|飞行员|交通
piscină|游泳池|运动
plajă|海滩|旅行
plată|付款|金融
plimbare|散步|日常
poartă|大门|城市
politician|政治家|社会
popor|民族|社会
porumb|玉米|饮食
posibilitate|可能性|学习
poșetă|手提包|购物
prânz|午饭|饮食
preț|价格|购物
prietene|朋友们|人际
privire|目光|人际
producție|生产|商业
produs|产品|购物
profesie|职业|职场
programare|预约|健康
progres|进步|学习
proprietar|房东|家居
prosperitate|繁荣|社会
protecție|保护|社会
publicitate|广告|商业
punct|点|学习
putere|力量|社会
raport|报告|职场
răbdare|耐心|情感
răspundere|责任|职场
recipient|容器|家居
reclamă|广告|商业
reducere|折扣|购物
regulă|规则|学习
relație|关系|人际
reparație|修理|家居
rețea|网络|科技
rezultat|结果|学习
ridicare|取件|购物
risc|风险|金融
rochie|连衣裙|购物
roșie|番茄|饮食
rușine|羞愧|情感
sâmbătă|星期六|时间
sat|村庄|地理
scop|目标|学习
scrisoare|信|人际
scutire|豁免|社会
seară|傍晚|时间
secret|秘密|人际
septembrie|九月|时间
serviciu|服务|职场
semn|标志|城市
semnal|信号|交通
sentiment|感受|情感
serie|系列|学习
sertar|抽屉|家居
sfat|建议|人际
siguranță|安全|社会
sistem|系统|科技
situație|情况|日常
societate|社会|社会
soluție|解决办法|学习
speranță|希望|情感
spumă|泡沫|家居
stare|状态|健康
stat|国家|社会
steag|旗帜|社会
sticlă|瓶子|饮食
stil|风格|艺术
străin|外国人|人际
succes|成功|学习
suflet|灵魂|情感
sumă|金额|金融
suprafață|表面|学习
surpriză|惊喜|情感
tablou|画作|艺术
tăcere|沉默|人际
taxă|费用|金融
tehnologie|技术|科技
temă|作业|教育
timp|时间|时间
tinerețe|青春|人际
toaletă|厕所|城市
tort|蛋糕|饮食
tradiție|传统|文化
trafic|交通|交通
tristețe|悲伤|情感
tur|游览|旅行
uimire|惊讶|情感
umăr|肩膀|身体
unitate|单位|学习
urcare|上车|交通
utilizator|用户|科技
vacanță|假期|旅行
valoare|价值|金融
vânzător|售货员|购物
variantă|版本|学习
vecinătate|附近|城市
vedere|视力|健康
verificare|检查|职场
viață|生活|日常
victorie|胜利|运动
vineri|星期五|时间
viteză|速度|交通
voce|声音|人际
vot|投票|社会
zgomot|噪音|城市
zonă|区域|城市
`;

const adjectives = `
absolut|绝对的|形容词
accesibil|可接近的|形容词
activ|活跃的|形容词
adânc|深的|形容词
agresiv|激进的|形容词
amar|苦的|形容词
amabil|亲切的|形容词
amplu|宽广的|形容词
apropiat|近的|形容词
ascuțit|锋利的|形容词
atent|细心的|形容词
atractiv|有吸引力的|形容词
bogat|富有的|形容词
cald|热的|形容词
central|中央的|形容词
clar|清楚的|形容词
comod|方便的|形容词
complet|完整的|形容词
comun|共同的|形容词
concret|具体的|形容词
curat|干净的|形容词
curios|好奇的|形容词
delicios|美味的|形容词
deschis|开放的|形容词
dificil|困难的|形容词
direct|直接的|形容词
disponibil|可用的|形容词
eficient|高效的|形容词
egal|平等的|形容词
elegant|优雅的|形容词
enorm|巨大的|形容词
exact|准确的|形容词
excelent|优秀的|形容词
fals|假的|形容词
familiar|熟悉的|形容词
fericit|幸福的|形容词
flexibil|灵活的|形容词
fraged|嫩的|形容词
frumos|美丽的|形容词
generos|慷慨的|形容词
greu|重的|形容词
ieftin|便宜的|形容词
imediat|立即的|形容词
independent|独立的|形容词
intens|强烈的|形容词
liniștit|安静的|形容词
local|本地的|形容词
lung|长的|形容词
matur|成熟的|形容词
moale|柔软的|形容词
natural|自然的|形容词
necesar|必要的|形容词
normal|正常的|形容词
nou|新的|形容词
oficial|官方的|形容词
optimist|乐观的|形容词
ordonat|整齐的|形容词
original|原创的|形容词
permanent|永久的|形容词
personal|个人的|形容词
plăcut|愉快的|形容词
popular|受欢迎的|形容词
pozitiv|积极的|形容词
practic|实用的|形容词
precis|精确的|形容词
profund|深刻的|形容词
rapid|快速的|形容词
rar|稀少的|形容词
recent|最近的|形容词
rezistent|耐用的|形容词
rotund|圆的|形容词
sănătos|健康的|形容词
scurt|短的|形容词
secret|秘密的|形容词
sensibil|敏感的|形容词
serios|严肃的|形容词
sincer|真诚的|形容词
singur|独自的|形容词
special|特别的|形容词
stabil|稳定的|形容词
subțire|薄的|形容词
suficient|足够的|形容词
surprins|惊讶的|形容词
tehnic|技术的|形容词
trist|悲伤的|形容词
ușor|轻的|形容词
util|有用的|形容词
vesel|开心的|形容词
viitor|未来的|形容词
vizibil|可见的|形容词
`;

const verbs = `
accepta|接受|动词
admira|欣赏|动词
aduce|带来|动词
afla|得知|动词
ajunge|到达|动词
alege|选择|动词
apărea|出现|动词
aprinde|点燃|动词
arăta|展示|动词
arunca|扔|动词
asculta|听|动词
aștepta|等待|动词
atinge|触摸|动词
auzi|听见|动词
bea|喝|动词
câștiga|赢得|动词
cere|请求|动词
chema|叫|动词
cheltui|花费|动词
circula|通行|动词
citi|阅读|动词
coborî|下去|动词
comanda|订购|动词
completa|填写|动词
cumpăra|购买|动词
cunoaște|认识|动词
curăța|清洁|动词
deschide|打开|动词
desena|画|动词
discuta|讨论|动词
dormi|睡觉|动词
expedia|寄送|动词
explica|解释|动词
face|做|动词
fotografia|拍照|动词
găsi|找到|动词
găti|做饭|动词
glumi|开玩笑|动词
greși|犯错|动词
învăța|学习|动词
închide|关闭|动词
începe|开始|动词
încerca|尝试|动词
înțelege|理解|动词
întreba|询问|动词
intra|进入|动词
ieși|出去|动词
iubi|爱|动词
juca|玩|动词
locui|居住|动词
lucra|工作|动词
lua|拿|动词
mânca|吃|动词
merge|走|动词
muta|搬动|动词
nota|记录|动词
observa|观察|动词
organiza|组织|动词
parca|停车|动词
participa|参加|动词
plăti|付款|动词
pleca|离开|动词
primi|收到|动词
pronunța|发音|动词
proteja|保护|动词
publica|发布|动词
purta|穿戴|动词
repara|修理|动词
repeta|重复|动词
rezolva|解决|动词
răspunde|回答|动词
rămâne|留下|动词
salva|保存|动词
schimba|改变|动词
scrie|写|动词
semna|签名|动词
simți|感觉|动词
spăla|洗|动词
spune|说|动词
sta|待着|动词
studia|学习|动词
trimite|发送|动词
uita|忘记|动词
urca|上去|动词
urmări|跟随|动词
verifica|核对|动词
vinde|出售|动词
vizita|参观|动词
vorbi|说话|动词
zâmbi|微笑|动词
`;

const adverbs = `
acasă|在家|副词
afară|在外面|副词
aproape|几乎|副词
azi|今天|副词
bine|好|副词
curând|很快|副词
departe|远地|副词
des|经常|副词
devreme|早|副词
greu|困难地|副词
ieri|昨天|副词
împreună|一起|副词
înapoi|向后|副词
înainte|向前|副词
încet|慢慢地|副词
mereu|总是|副词
mâine|明天|副词
niciodată|从不|副词
repede|快速地|副词
târziu|晚|副词
totuși|然而|副词
`;

const supplement = `
abilitate|能力|学习
abonament|订阅|商业
absență|缺席|教育
abuz|滥用|社会
accent|口音|学习
acceptare|接受|人际
acoperiș|屋顶|家居
acțiune|行动|社会
adevăr|真相|人际
administrație|行政|社会
adolescent|青少年|人际
adunare|集合|社会
afirmare|肯定|人际
agent|代理人|职场
agitație|骚动|情感
agricultură|农业|自然
alee|小路|城市
ambasador|大使|社会
ambasada|大使馆|城市
amenajare|布置|家居
amendă|罚款|社会
amiază|中午|时间
amprentă|指纹|社会
antrenament|训练|运动
anunț|通知|社会
aparat|设备|科技
apărare|防御|社会
aprobare|批准|职场
arhitect|建筑师|职场
aripă|翅膀|自然
arhivă|档案|职场
articol|文章|学习
asigurare|保险|金融
asociație|协会|社会
atitudine|态度|人际
atracție|吸引力|旅行
audiență|听众|艺术
autoritate|权威|社会
avertisment|警告|社会
avocat|律师|社会
azil|收容所|社会
bal|舞会|文化
bancnotă|纸币|金融
barieră|障碍|交通
baston|手杖|健康
bazaar|集市|购物
bibliotecar|图书管理员|职场
bijuterie|首饰|购物
blândețe|温柔|情感
boabe|豆粒|饮食
bonus|奖金|金融
bucătar|厨师|烹饪
bumbac|棉花|购物
buric|肚脐|身体
bursier|奖学金生|教育
cafeină|咖啡因|饮食
campionat|锦标赛|运动
candidat|候选人|社会
canapea|沙发|家居
cantitate|数量|购物
caracteristică|特征|学习
casier|收银员|购物
ceainic|茶壶|家居
celulă|细胞|身体
centură|腰带|购物
cercetare|研究|教育
cerneală|墨水|学习
cheie|钥匙|家居
chitarist|吉他手|艺术
chitanță|收据|购物
chestionar|问卷|学习
chirurg|外科医生|健康
cifră|数字|学习
cinste|诚实|人际
cireașă|樱桃|饮食
cititor|读者|学习
coafor|理发店|城市
coapsă|大腿|身体
coborâre|下降|交通
cod|代码|科技
colaborare|合作|职场
colet|包裹|购物
coloană|柱子|城市
combustibil|燃料|交通
comisie|委员会|社会
compasiune|同情|情感
competent|有能力的|形容词
comunitate|社区|社会
concert|音乐会|艺术
concurs|比赛|教育
condiție|条件|职场
conflict|冲突|社会
confort|舒适|家居
consimțământ|同意|社会
construcție|建筑工程|城市
consultant|顾问|职场
consum|消费|商业
contact|联系|人际
copilărie|童年|人际
corupție|腐败|社会
cravată|领带|购物
cremă|乳霜|购物
creșă|托儿所|教育
criteriu|标准|学习
croitor|裁缝|职场
cub|立方体|学习
cunoștințe|知识|学习
curățenie|清洁|家居
curiozitate|好奇心|情感
cursant|学员|教育
cutremur|地震|自然
debit|流量|科技
defect|缺陷|购物
delegat|代表|职场
demnitate|尊严|社会
depozit|仓库|商业
desert|甜点|饮食
destinație|目的地|旅行
detectiv|侦探|社会
dezastru|灾难|自然
dezbatere|辩论|教育
dezvoltare|发展|社会
diagnostic|诊断|健康
difuzor|扬声器|科技
director|导演|艺术
disciplină|纪律|教育
dispozitiv|装置|科技
diversitate|多样性|社会
dobândă|利息|金融
domeniu|领域|学习
donație|捐赠|社会
dorință|愿望|情感
dovleac|南瓜|饮食
dreptate|正义|社会
duș|淋浴|家居
duzină|一打|数量
ecou|回声|自然
editură|出版社|文化
educator|教育工作者|教育
eficiență|效率|职场
egalitate|平等|社会
echipaj|乘务组|交通
echipament|装备|运动
ecran|屏幕|科技
editor|编辑|职场
emoțional|情绪的|形容词
entuziasm|热情|情感
episod|集|艺术
eroare|错误|科技
esență|本质|学习
etapă|阶段|学习
evidență|记录|职场
excepție|例外|学习
exercițiu|练习|运动
exigență|要求|学习
expediere|发货|购物
expert|专家|职场
faianță|瓷砖|家居
farmacist|药剂师|健康
favoare|帮忙|人际
febră|发烧|健康
fermoar|拉链|购物
fiabilitate|可靠性|科技
fibra|纤维|健康
ficțiune|小说类|艺术
filtru|过滤器|科技
finanțare|融资|金融
firmă|公司|商业
fluture|蝴蝶|自然
foaie|纸张|学习
folos|用处|日常
forță|力量|健康
frână|刹车|交通
frecvență|频率|学习
front|前线|社会
fruct|水果|饮食
fum|烟|自然
fundal|背景|艺术
furt|盗窃|社会
gaj|抵押|金融
garanție|保证|购物
gard|围栏|家居
gazdă|主人|人际
generație|一代|社会
geografie|地理|教育
geologie|地质|自然
gestionare|管理|职场
ghicitoare|谜语|文化
ghișeu|窗口|城市
glorie|荣耀|情感
gol|空的|形容词
gospodărie|家务|家居
grad|程度|学习
grafic|图表|学习
graniță|边境|地理
grăsime|脂肪|健康
grâu|小麦|饮食
greșeală|错误|学习
gustare|小吃|饮食
halat|长袍|购物
hârtie|纸|学习
hotărâre|决定|职场
hrană|食物|饮食
identitate|身份|社会
igienă|卫生|健康
ilustrație|插图|艺术
impozit|税款|金融
incident|事件|社会
indiciu|线索|学习
inflație|通货膨胀|金融
inițiativă|倡议|职场
injecție|注射|健康
inovație|创新|科技
instanță|法庭|社会
instituție|机构|社会
inteligență|智力|学习
interdicție|禁令|社会
interfață|界面|科技
interpret|口译员|职场
intimitate|隐私|人际
ipoteză|假设|学习
istorie|历史|教育
izolare|隔离|健康
împrumut|贷款|金融
încălzire|加热|家居
încredere|信任|人际
îndemânare|技巧|学习
întârziere|延误|交通
întreținere|维护|家居
jale|悲痛|情感
jaluzea|百叶窗|家居
jar|炭火|自然
jeans|牛仔裤|购物
jurământ|誓言|社会
justiție|司法|社会
kilometraj|里程|交通
laborant|实验员|职场
lacăt|挂锁|家居
lapoviță|雨夹雪|天气
legislație|法规|社会
leziune|损伤|健康
licitație|拍卖|商业
lider|领导者|职场
limbaj|语言表达|学习
lichid|液体|自然
livrare|配送|购物
logică|逻辑|学习
loialitate|忠诚|人际
loterie|彩票|金融
macara|起重机|城市
magnet|磁铁|科技
majoritate|多数|社会
mandat|任期|社会
manevră|操作|交通
marfă|货物|商业
marjă|利润率|金融
mărturie|证词|社会
mătase|丝绸|购物
medicament|药物|健康
memorie|记忆|学习
menaj|家务|家居
mentenanță|维护|科技
mercenar|雇佣兵|社会
merit|功劳|学习
mesaj|消息|科技
meșteșug|手艺|文化
metrou|地铁|交通
microfon|麦克风|科技
migrație|迁移|社会
milioane|百万|数量
minciună|谎言|人际
miner|矿工|职场
miracol|奇迹|情感
misiune|任务|职场
mizerie|脏乱|家居
mobilier|家具|家居
moștenire|遗产|社会
motivare|激励|职场
mulțime|人群|社会
narațiune|叙述|艺术
națiune|国家|社会
negociere|谈判|商业
nerv|神经|身体
notificare|通知|科技
nuanță|色调|艺术
obiectiv|目标|学习
obligație|义务|社会
observație|观察|学习
ochelari|眼镜|健康
oficial|官员|社会
oglindire|反映|学习
operator|操作员|职场
opțiune|选项|科技
orășel|小镇|城市
ordine|命令|职场
origine|起源|学习
orizont|视野|学习
ospitalitate|好客|文化
otravă|毒药|健康
pâine|面包|饮食
palat|宫殿|城市
palton|大衣|购物
panou|面板|科技
paragraf|段落|学习
parfum|香水|购物
partener|伙伴|人际
pas|步骤|学习
patrimoniu|遗产|文化
pauză|休息|日常
pavilion|展馆|城市
perdea|窗帘|家居
performanță|表现|职场
periferie|郊区|城市
permisie|许可|社会
perspectivă|视角|学习
pescar|渔民|职场
petală|花瓣|自然
piață|市场|购物
pieton|行人|交通
piloți|飞行员们|交通
plic|信封|人际
ploaie|雨|天气
pod|桥|城市
polițist|警察|社会
pompier|消防员|职场
populație|人口|社会
porție|一份|饮食
port|港口|交通
portocală|橙子|饮食
poziție|位置|方向
prietenie|友谊|人际
probă|样本|学习
procedură|流程|职场
proces|过程|学习
producător|生产者|商业
profesor|教师|教育
profit|利润|金融
promisiune|承诺|人际
propunere|建议|职场
prosop|毛巾|家居
public|公众|社会
pulover|毛衣|购物
rachetă|火箭|科技
radar|雷达|交通
rafinament|精致|艺术
ramură|树枝|自然
rată|分期款|金融
răceală|感冒|健康
recenzie|评论|艺术
reciprocitate|互惠|人际
recompensă|奖励|职场
recrutare|招聘|职场
refuz|拒绝|人际
regizor|导演|艺术
regret|遗憾|情感
rețetă|食谱|烹饪
rețetă|处方|健康
rezervor|油箱|交通
rezistență|耐力|健康
robust|结实的|形容词
rucsac|背包|旅行
salariu|工资|金融
săpun|肥皂|购物
scandal|丑闻|社会
scară|楼梯|城市
sceptic|怀疑的|形容词
schiță|草图|艺术
scriitor|作家|艺术
scurtătură|捷径|交通
secol|世纪|时间
senator|参议员|社会
servietă|公文包|职场
sesiune|场次|教育
sever|严厉的|形容词
sfârșit|结束|时间
sigiliu|印章|职场
siluetă|轮廓|艺术
sindrom|综合征|健康
singurătate|孤独|情感
sinteză|综合|学习
sirenă|警笛|城市
slăbiciune|虚弱|健康
slujbă|工作|职场
sol|土壤|自然
sold|余额|金融
sondaj|调查|社会
spațiu|空间|城市
spate|背部|身体
specialist|专家|职场
spectacol|演出|艺术
spitalizare|住院|健康
strategie|策略|职场
stres|压力|健康
subiect|主题|学习
subsol|地下室|家居
suferință|痛苦|情感
sugestie|建议|人际
supraveghere|监督|社会
surâs|微笑|情感
surub|螺丝|家居
susținere|支持|人际
șansă|机会|人际
ședință|会议|职场
șervețel|餐巾|饮食
șofer|司机|交通
tabără|营地|旅行
tactică|战术|运动
talent|天赋|艺术
tavan|天花板|家居
tăietură|切口|健康
tărie|强度|学习
teanc|一叠|学习
tencuială|灰泥|家居
teorie|理论|学习
terapie|治疗|健康
termen|期限|职场
terorism|恐怖主义|社会
tezaur|宝库|文化
tichet|票券|交通
tigru|老虎|自然
tipar|模板|学习
tiraj|发行量|商业
tocană|炖菜|饮食
tomberon|垃圾桶|城市
trai|生活|日常
traseu|路线|交通
tratat|条约|社会
tribună|看台|运动
truc|技巧|学习
trup|身体|身体
tunel|隧道|交通
turmă|群|自然
ucenic|学徒|职场
ulei|油|烹饪
umbră|阴影|自然
umilință|羞辱|情感
unchi|叔叔|人际
uniformă|制服|购物
urgență|紧急情况|健康
usturoi|大蒜|饮食
utilitate|实用性|日常
vagon|车厢|交通
valiză|行李箱|旅行
vapor|轮船|交通
varză|卷心菜|饮食
vârstă|年龄|人际
vânt|风|天气
verdict|判决|社会
vestă|背心|购物
veșnicie|永恒|情感
victimă|受害者|社会
videoclip|视频短片|科技
vigilent|警觉的|形容词
viitor|未来|时间
violență|暴力|社会
vioară|小提琴|艺术
vizibilitate|能见度|天气
vocabular|词汇|学习
voință|意志|情感
volan|方向盘|交通
volum|音量|科技
vreme|天气|天气
zar|骰子|游戏
zbor|航班|交通
zestre|嫁妆|文化
ziar|报纸|文化
zid|墙|城市
zmeură|覆盆子|饮食
`;

function rowsFromBlock(block) {
  return block.trim().split('\n').filter(Boolean).map(line => {
    const [ro, zh, cat] = line.split('|');
    return { zh, ro, ipa: '', hint: '', cat };
  });
}

function adjectiveVariants(row) {
  const forms = [row];
  const ro = row.ro;
  const zh = row.zh;
  if (ro.endsWith('os')) forms.push({ ...row, ro: ro.slice(0, -2) + 'oasă', zh: `${zh}（阴性）` });
  else if (ro.endsWith('at')) forms.push({ ...row, ro: ro.slice(0, -2) + 'ată', zh: `${zh}（阴性）` });
  else if (ro.endsWith('it')) forms.push({ ...row, ro: ro.slice(0, -2) + 'ită', zh: `${zh}（阴性）` });
  else if (ro.endsWith('ut')) forms.push({ ...row, ro: ro.slice(0, -2) + 'ută', zh: `${zh}（阴性）` });
  else if (ro.endsWith('iv')) forms.push({ ...row, ro: ro.slice(0, -2) + 'ivă', zh: `${zh}（阴性）` });
  else if (ro.endsWith('ic')) forms.push({ ...row, ro: ro.slice(0, -2) + 'ică', zh: `${zh}（阴性）` });
  else if (ro.endsWith('al')) forms.push({ ...row, ro: ro.slice(0, -2) + 'ală', zh: `${zh}（阴性）` });
  else if (ro.endsWith('ar')) forms.push({ ...row, ro: ro.slice(0, -2) + 'ară', zh: `${zh}（阴性）` });
  return forms;
}

function verbForms(row) {
  const ro = row.ro;
  const forms = [row];
  const regularA = ro.endsWith('a') && !ro.endsWith('ea');
  const regularI = ro.endsWith('i') || ro.endsWith('î');
  if (regularA) {
    const stem = ro.slice(0, -1);
    forms.push({ ...row, ro: stem + 'at', zh: `${row.zh}过` });
  } else if (regularI) {
    const stem = ro.slice(0, -1);
    forms.push({ ...row, ro: stem + 'it', zh: `${row.zh}过` });
  }
  return forms;
}

function main() {
  const seen = new Set();
  const out = [];
  const push = row => {
    if (!row.ro || row.ro.includes(' ')) return;
    const key = row.ro.toLocaleLowerCase('ro-RO');
    if (seen.has(key)) return;
    seen.add(key);
    out.push(row);
  };

  rowsFromBlock(seeds).forEach(push);
  rowsFromBlock(supplement).forEach(push);
  rowsFromBlock(adjectives).flatMap(adjectiveVariants).forEach(push);
  rowsFromBlock(verbs).flatMap(verbForms).forEach(push);
  rowsFromBlock(adverbs).forEach(push);

  process.stdout.write(JSON.stringify(out, null, 2));
}

main();
