create table if not exists public.pending_words (
  id bigint generated by default as identity primary key,
  zh text,
  ro text not null,
  ipa text default '',
  hint text default '',
  cat text default 'Daily Life',
  example_ro text default '',
  example_zh text default '',
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  submitted_by uuid references auth.users(id) on delete set null,
  submitted_email text,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists pending_words_status_created_idx
  on public.pending_words (status, created_at desc);

alter table public.pending_words enable row level security;

create policy "Admins can read pending words"
  on public.pending_words for select
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
        and profiles.role = 'admin'
    )
  );

create policy "Admins can submit pending words"
  on public.pending_words for insert
  with check (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
        and profiles.role = 'admin'
    )
  );

create policy "Admins can review pending words"
  on public.pending_words for update
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
        and profiles.role = 'admin'
    )
  )
  with check (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
        and profiles.role = 'admin'
    )
  );
