const assert = require('assert');
const fs = require('fs');
const path = require('path');

const api = fs.readFileSync(path.join(__dirname, '..', 'api.js'), 'utf8');
const app = fs.readFileSync(path.join(__dirname, '..', 'app.js'), 'utf8');

assert(api.includes('function dailyStatePendingKey'), 'daily state must have a durable pending key');
assert(api.includes('function queueDailyStateForSync'), 'daily state writes must enter a pending queue');
assert(api.includes('function clearPendingDailyStatePart'), 'daily state pending entries must be cleared only after cloud success');
assert(api.includes('function apiRetryPendingDailyState'), 'daily state pending entries must have an explicit retry worker');
assert(api.includes('function apiGetPendingSyncSummary'), 'UI must derive pending counts from durable local queues');
assert(api.includes('function apiVerifyTodayState'), 'manual sync must verify today state with a cloud read-back');
assert(api.includes('function apiVerifyProgressState'), 'manual sync must verify all progress with a cloud read-back');
assert(api.includes('queueDailyStateForSync(userId, today, { queue: payload })'), 'daily queue saves must be queued before cloud sync');
assert(api.includes('queueDailyStateForSync(userId, today, { log: localPayload })'), 'daily log saves must be queued before cloud sync');
assert(api.includes('function createDailySyncToken'), 'daily pending writes must have per-write sync tokens');
assert(api.includes('function createProgressSyncToken'), 'progress pending writes must have per-write sync tokens');
assert(api.includes('clearPendingDailyEvent(userId, event.eventId)'), 'a daily event must clear only after the RPC confirms it');
assert(api.includes('event.tokens?.[part]'), 'snapshot pending state must clear using the confirmed event token');
assert(api.includes('currentToken !== syncedToken'), 'pending clear must not delete a newer local write with a different token');
assert(api.includes('pendingSyncToken: createProgressSyncToken(key)'), 'progress pending writes must store token');
assert(api.includes('clearPendingProgress(userId, wordId, wordRo, expectedToken)'), 'progress retry must clear only the saved pending token');
assert(!api.includes('updated_at|schema cache|Could not find'), 'daily log sync must fail closed instead of silently dropping updated_at');
assert(api.includes("sb.rpc('apply_daily_state_sync_event'"), 'daily state must use the atomic server RPC');
assert(api.includes('p_state_date: event.date'), 'daily retries must preserve the original pending date');
assert(!api.includes("from('daily_queue').upsert"), 'daily queue snapshots must not use unconditional upsert');
assert(!api.includes("from('daily_log').upsert"), 'daily log snapshots must not use unconditional upsert');
assert(api.includes('readPendingDailyState(userId)?.[today]?.queue'), 'daily queue reads must overlay pending queue state');
assert(api.includes('readPendingDailyState(userId)?.[today]?.log'), 'today log reads must overlay pending log state');
assert(api.includes('pendingLogs'), 'recent logs must include pending local logs');
assert(api.includes('Object.keys(readPendingProgress(userId)).length'), 'progress retry remaining count must include writes created during an in-flight retry');
assert(api.includes('pendingCorrection'), 'undo corrections must override monotonic progress merging');
assert(api.includes('applyDailyQueueEventLocally'), 'daily rollback must be represented as a reversible base-target delta');
assert(api.includes('introduced_word_id'), 'daily new-card introductions must be part of the synchronized queue state');
assert(api.includes('Number(cloudLog.new_words || 0) === expectedProcessed'), 'cloud verification must require the exact post-undo daily count');
assert(api.includes('sameSet(expectedOpenIds, cloudOpenIds)'), 'cloud verification must reject extra or missing queue cards');
assert(api.includes('sameSet(expectedIntroducedIds, cloudIntroducedIds)'), 'cloud verification must include the daily new-card cap state');
assert(api.includes('const DAILY_STATE_TIMEOUT_MS = 12000'), 'daily state sync must tolerate normal long-distance network latency');
assert(!api.includes('function selectLatestDailyPayload'), 'client timestamps must not choose authoritative daily state');
assert(api.includes('function applyIdArrayDelta'), 'daily array changes must be applied as membership deltas');
assert(api.includes('const countDelta = target.new_words - base.new_words'), 'daily counters must be synchronized as deltas');
assert(api.includes('updated_at: queue.updated_at || queue.updatedAt || new Date().toISOString()'), 'local queue snapshots must preserve merge ordering evidence');
assert(api.includes('request.abortSignal(controller.signal)'), 'timed-out Supabase requests must actually be aborted');
assert(api.includes("db: { retry: false }"), 'opaque automatic POST retries must be disabled');
assert(api.includes('function dailyStateEventPrefix'), 'each daily event must have a unique durable storage key');
assert(api.includes('function progressEventJournalPrefix'), 'progress events must survive cross-tab localStorage races');
assert(api.includes('function syncPendingDailyEventsThrough'), 'daily sync must drain failed predecessor events before a later delta');

assert(app.includes('function hasPendingSync'), 'UI sync state must include daily pending state');
assert(app.includes('function reconcileProgressPendingFlags'), 'UI flags must be reconciled from the durable pending queue after retry');
assert(app.includes('apiRetryPendingDailyState(currentUser.id)'), 'app must retry daily pending state');
assert(app.includes("window.addEventListener('online'"), 'app must retry when the network comes back');
assert(app.includes('if (!hasPendingSync()) setSyncBadge'), 'sync badge must not clear while any pending state remains');
assert(app.includes('retryPendingProgressAfterLoad();'), 'startup must trigger pending retry');
assert(app.includes('|| hasPendingSync()'), 'progress refresh success must not mask daily pending state');
assert(app.includes('&& !hasDailyPending'), 'daily pending startup retry must not be blocked by progress cooldown');
assert(app.includes("triggerCloudProgressBackup('启动同步'"), 'startup retry must use the shared in-flight sync path');
assert(app.includes('if (!hasPendingSync() && !options.force) return null'), 'clean idle sync should skip no-op cloud writes');
assert(!app.includes('Object.keys(progressMap).forEach((wordRo)'), 'sync success must not blindly clear flags for writes created during the request');

console.log('daily sync pending verification passed');
